--[   NPD_MSPROJECTS_TASKS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF TASKS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_TASKS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
TASKS_KEY
, SNAPSHOT_WEEK_KEY
,PROJECTID
, TASKID
, DETECTABILITY
, FLAGSTATUS
, HEALTH
, IMPACT
, MITIGATIONFLAG
, NPDGATE
, NPDMILESTONE
, PARENTTASKID
, PARENTTASKNAME
, PROBABILITY
, PROJECTNAME
, RISK
, RISKFLAG
, RISKLEVEL
, RISKSCORE
, TASKACTUALCOST
, TASKACTUALDURATION
, TASKACTUALFINISHDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKACTUALFINISHDATE) AS BIW_TASKACTUALFINISHDATE_MST
, TASKACTUALFIXEDCOST
, TASKACTUALOVERTIMECOST
, TASKACTUALOVERTIMEWORK
, TASKACTUALREGULARCOST
, TASKACTUALREGULARWORK
, TASKACTUALSTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKACTUALSTARTDATE) AS BIW_TASKACTUALSTARTDATE_MST
, TASKACTUALWORK
, TASKACWP
, TASKBCWP
, TASKBCWS
, TASKBUDGETCOST
, TASKBUDGETWORK
, TASKCLIENTUNIQUEID
, TASKCOST
, TASKCOSTVARIANCE
, TASKCPI
, TASKCREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKCREATEDDATE) AS BIW_TASKCREATEDDATE_MST
, TASKCREATEDREVISIONCOUNTER
, TASKCV
, TASKCVP
, TASKDEADLINE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKDEADLINE) AS BIW_TASKDEADLINE_MST
, TASKDELIVERABLEFINISHDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKDELIVERABLEFINISHDATE) AS BIW_TASKDELIVERABLEFINISHDATE_MST
, TASKDELIVERABLESTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKDELIVERABLESTARTDATE) AS BIW_TASKDELIVERABLESTARTDATE_MST
, TASKDURATION
, TASKDURATIONISESTIMATED
, TASKDURATIONSTRING
, TASKDURATIONVARIANCE
, TASKEAC
, TASKEARLYFINISH , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKEARLYFINISH) AS BIW_TASKEARLYFINISH_MST
, TASKEARLYSTART , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKEARLYSTART) AS BIW_TASKEARLYSTART_MST
, TASKFINISHDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKFINISHDATE) AS BIW_TASKFINISHDATE_MST
, TASKFINISHDATESTRING
, TASKFINISHVARIANCE
, TASKFIXEDCOST
, TASKFIXEDCOSTASSIGNMENTID
, TASKFREESLACK
, TASKHYPERLINKADDRESS
, TASKHYPERLINKFRIENDLYNAME
, TASKHYPERLINKSUBADDRESS
, TASKIGNORESRESOURCECALENDAR
, TASKINDEX
, TASKISACTIVE
, TASKISCRITICAL
, TASKISEFFORTDRIVEN
, TASKISEXTERNAL
, TASKISMANUALLYSCHEDULED
, TASKISMARKED
, TASKISMILESTONE
, TASKISOVERALLOCATED
, TASKISPROJECTSUMMARY
, TASKISRECURRING
, TASKISSUMMARY
, TASKLATEFINISH , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKLATEFINISH) AS BIW_TASKLATEFINISH_MST
, TASKLATESTART , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKLATESTART) AS BIW_TASKLATESTART_MST
, TASKLEVELINGDELAY
, TASKMODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKMODIFIEDDATE) AS BIW_TASKMODIFIEDDATE_MST
, TASKMODIFIEDREVISIONCOUNTER
, TASKNAME
, TASKOUTLINELEVEL
, TASKOUTLINENUMBER
, TASKOVERTIMECOST
, TASKOVERTIMEWORK
, TASKPERCENTCOMPLETED
, TASKPERCENTWORKCOMPLETED
, TASKPHYSICALPERCENTCOMPLETED
, TASKPRIORITY
, TASKREGULARCOST
, TASKREGULARWORK
, TASKREMAININGCOST
, TASKREMAININGDURATION
, TASKREMAININGOVERTIMECOST
, TASKREMAININGOVERTIMEWORK
, TASKREMAININGREGULARCOST
, TASKREMAININGREGULARWORK
, TASKREMAININGWORK
, TASKRESOURCEPLANWORK
, TASKSPI
, TASKSTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKSTARTDATE) AS BIW_TASKSTARTDATE_MST
, TASKSTARTDATESTRING
, TASKSTARTVARIANCE
, TASKSTATUSMANAGERUID
, TASKSV
, TASKSVP
, TASKTCPI
, TASKTOTALSLACK
, TASKVAC
, TASKWBS
, TASKWORK
, TASKWORKVARIANCE
, LINKEDASSIGNMENTS
, LINKEDASSIGNMENTSBASELINES
, LINKEDASSIGNMENTSBASELINETIMEPHASEDDATA
, LINKEDBASELINES
, LINKEDBASELINESTIMEPHASEDDATASET
, LINKEDISSUES
, LINKEDPROJECT
, LINKEDRISKS
, LINKEDTIMEPHASEDINFO
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_TASKS_WEEKLY_SNAPSHOT')}}  
