--[   NPD_MSPROJECTS_TIMESHEETLINES_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF TIMESHEETLINES ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_TIMESHEETLINES_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
TIMESHEETLINES_KEY
, SNAPSHOT_WEEK_KEY
,TIMESHEETLINEID
, ACTUALOVERTIMEWORKBILLABLE
, ACTUALOVERTIMEWORKNONBILLABLE
, ACTUALWORKBILLABLE
, ACTUALWORKNONBILLABLE
, ASSIGNMENTID
, CREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',CREATEDDATE) AS BIW_CREATEDDATE_MST
, LASTSAVEDWORK
, LCID
, MODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',MODIFIEDDATE) AS BIW_MODIFIEDDATE_MST
, PERIODENDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PERIODENDDATE) AS BIW_PERIODENDDATE_MST
, PERIODSTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PERIODSTARTDATE) AS BIW_PERIODSTARTDATE_MST
, PLANNEDWORK
, PROJECTID
, PROJECTNAME
, TASKHIERARCHY
, TASKID
, TASKNAME
, TIMESHEETAPPROVERRESOURCEID
, TIMESHEETAPPROVERRESOURCENAME
, TIMESHEETCLASSDESCRIPTION
, TIMESHEETCLASSID
, TIMESHEETCLASSNAME
, TIMESHEETCLASSTYPE
, TIMESHEETID
, TIMESHEETLINECOMMENT
, TIMESHEETLINESTATUS
, TIMESHEETLINESTATUSID
, TIMESHEETNAME
, TIMESHEETOWNER
, TIMESHEETOWNERID
, TIMESHEETPERIODID
, TIMESHEETPERIODNAME
, TIMESHEETPERIODSTATUS
, TIMESHEETPERIODSTATUSID
, TIMESHEETSTATUS
, TIMESHEETSTATUSID
, LINKEDACTUALS
, LINKEDAPPROVERRESOURCE
, LINKEDTIMESHEET
, LINKEDTIMESHEETCLASS
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_TIMESHEETLINES_WEEKLY_SNAPSHOT')}}  
