--[   NPD_MSPROJECTS_RESOURCESCENARIOPROJECTS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF RESOURCESCENARIOPROJECTS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_RESOURCESCENARIOPROJECTS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
RESOURCESCENARIOPROJECTS_KEY
, SNAPSHOT_WEEK_KEY
,PROJECTID
, SCENARIOID
, ABSOLUTEPRIORITY
, ANALYSISID
, ANALYSISNAME
, COSTCONSTRAINTSCENARIOID
, COSTCONSTRAINTSCENARIONAME
, FORCEALIASLOOKUPTABLEID
, FORCEALIASLOOKUPTABLENAME
, FORCESTATUS
, HARDCONSTRAINTVALUE
, NEWSTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',NEWSTARTDATE) AS BIW_NEWSTARTDATE_MST
, PRIORITY
, PROJECTNAME
, RESOURCECOST
, RESOURCEWORK
, SCENARIONAME
, STATUS
, LINKEDANALYSIS
, LINKEDCOSTCONSTRAINTSCENARIO
, LINKEDPROJECT
, LINKEDRESOURCECONSTRAINTSCENARIO
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_RESOURCESCENARIOPROJECTS_WEEKLY_SNAPSHOT')}}  
