--[   NPD_MSPROJECTS_TIMESHEETPERIODS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF TIMESHEETPERIODS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_TIMESHEETPERIODS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
TIMESHEETPERIODS_KEY
, SNAPSHOT_WEEK_KEY
,PERIODID
, DESCRIPTION
, ENDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',ENDDATE) AS BIW_ENDDATE_MST
, LCID
, PERIODNAME
, PERIODSTATUSID
, STARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',STARTDATE) AS BIW_STARTDATE_MST
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_TIMESHEETPERIODS_WEEKLY_SNAPSHOT')}}  
