--[   NPD_MSPROJECTS_PROJECTBASELINES_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF PROJECTBASELINES ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_PROJECTBASELINES_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
PROJECTBASELINES_KEY
, SNAPSHOT_WEEK_KEY
,BASELINENUMBER
, PROJECTID
, PROJECTBASELINEBUDGETCOST
, PROJECTBASELINEBUDGETWORK
, PROJECTBASELINECOST
, PROJECTBASELINEDELIVERABLEFINISHDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTBASELINEDELIVERABLEFINISHDATE) AS BIW_PROJECTBASELINEDELIVERABLEFINISHDATE_MST
, PROJECTBASELINEDELIVERABLESTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTBASELINEDELIVERABLESTARTDATE) AS BIW_PROJECTBASELINEDELIVERABLESTARTDATE_MST
, PROJECTBASELINEDURATION
, PROJECTBASELINEDURATIONSTRING
, PROJECTBASELINEFINISHDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTBASELINEFINISHDATE) AS BIW_PROJECTBASELINEFINISHDATE_MST
, PROJECTBASELINEFINISHDATESTRING
, PROJECTBASELINEFIXEDCOST
, PROJECTBASELINEMODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTBASELINEMODIFIEDDATE) AS BIW_PROJECTBASELINEMODIFIEDDATE_MST
, PROJECTBASELINESTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTBASELINESTARTDATE) AS BIW_PROJECTBASELINESTARTDATE_MST
, PROJECTBASELINESTARTDATESTRING
, PROJECTBASELINEWORK
, PROJECTNAME
, TASKID
, LINKEDPROJECT
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_PROJECTBASELINES_WEEKLY_SNAPSHOT')}}  
