--[   NPD_MSPROJECTS_COSTCONSTRAINTSCENARIOS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF COSTCONSTRAINTSCENARIOS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_COSTCONSTRAINTSCENARIOS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
COSTCONSTRAINTSCENARIOS_KEY
, SNAPSHOT_WEEK_KEY
,SCENARIOID
, ANALYSISID
, ANALYSISNAME
, CREATEDBYRESOURCEID
, CREATEDBYRESOURCENAME
, CREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',CREATEDDATE) AS BIW_CREATEDDATE_MST
, MODIFIEDBYRESOURCEID
, MODIFIEDBYRESOURCENAME
, MODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',MODIFIEDDATE) AS BIW_MODIFIEDDATE_MST
, SCENARIODESCRIPTION
, SCENARIONAME
, SELECTEDPROJECTSCOST
, SELECTEDPROJECTSPRIORITY
, UNSELECTEDPROJECTSCOST
, UNSELECTEDPROJECTSPRIORITY
, USEDEPENDENCIES
, LINKEDANALYSIS
, LINKEDCOSTSCENARIOPROJECTS
, LINKEDCREATEDBYRESOURCE
, LINKEDMODIFIEDBYRESOURCE
, LINKEDRESOURCECONSTRAINTSCENARIOS
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_COSTCONSTRAINTSCENARIOS_WEEKLY_SNAPSHOT')}}  
