--[   NPD_MSPROJECTS_FISCALPERIODS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF FISCALPERIODS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_FISCALPERIODS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
FISCALPERIODS_KEY
, SNAPSHOT_WEEK_KEY
,FISCALPERIODID
, CREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',CREATEDDATE) AS BIW_CREATEDDATE_MST
, FISCALPERIODFINISH , CONVERT_TIMEZONE('UTC','America/Phoenix',FISCALPERIODFINISH) AS BIW_FISCALPERIODFINISH_MST
, FISCALPERIODMODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',FISCALPERIODMODIFIEDDATE) AS BIW_FISCALPERIODMODIFIEDDATE_MST
, FISCALPERIODNAME
, FISCALPERIODQUARTER
, FISCALPERIODSTART , CONVERT_TIMEZONE('UTC','America/Phoenix',FISCALPERIODSTART) AS BIW_FISCALPERIODSTART_MST
, FISCALPERIODYEAR
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_FISCALPERIODS_WEEKLY_SNAPSHOT')}}  
