--[   NPD_MSPROJECTS_ISSUES_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF ISSUES ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_ISSUES_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
ISSUES_KEY
, SNAPSHOT_WEEK_KEY
,ISSUEID
, PROJECTID
, ASSIGNEDTORESOURCE
, CATEGORY
, CREATEBYRESOURCE
, CREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',CREATEDDATE) AS BIW_CREATEDDATE_MST
, DISCUSSION
, DUEDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',DUEDATE) AS BIW_DUEDATE_MST
, ISFOLDER
, ITEMRELATIVEURLPATH
, MODIFIEDBYRESOURCE
, MODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',MODIFIEDDATE) AS BIW_MODIFIEDDATE_MST
, NUMBEROFATTACHMENTS
, OWNER
, PRIORITY
, PROJECTNAME
, RESOLUTION
, STATUS
, TITLE
, LINKEDPROJECT
, LINKEDRELATEDRISKS
, LINKEDSUBISSUES
, LINKEDTASKS
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_ISSUES_WEEKLY_SNAPSHOT')}}  
