--[   NPD_MSPROJECTS_RESOURCECONSTRAINTSCENARIOS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF RESOURCECONSTRAINTSCENARIOS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_RESOURCECONSTRAINTSCENARIOS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
RESOURCECONSTRAINTSCENARIOS_KEY
, SNAPSHOT_WEEK_KEY
,SCENARIOID
, ALLOCATIONTHRESHOLD
, ANALYSISID
, ANALYSISNAME
, CONSTRAINTTYPE
, CONSTRAINTVALUE
, COSTCONSTRAINTSCENARIOID
, COSTCONSTRAINTSCENARIONAME
, CREATEDBYRESOURCEID
, CREATEDBYRESOURCENAME
, CREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',CREATEDDATE) AS BIW_CREATEDDATE_MST
, ENFORCEPROJECTDEPENDENCIES
, ENFORCESCHEDULINGCONSTRAINTS
, HIRINGTYPE
, MODIFIEDBYRESOURCEID
, MODIFIEDBYRESOURCENAME
, MODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',MODIFIEDDATE) AS BIW_MODIFIEDDATE_MST
, RATETABLE
, SCENARIODESCRIPTION
, SCENARIONAME
, LINKEDANALYSIS
, LINKEDCOSTCONSTRAINTSCENARIO
, LINKEDCREATEDBYRESOURCE
, LINKEDMODIFIEDBYRESOURCE
, LINKEDRESOURCESCENARIOPROJECTS
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_RESOURCECONSTRAINTSCENARIOS_WEEKLY_SNAPSHOT')}}  
