--[   NPD_MSPROJECTS_BUSINESSDRIVERDEPARTMENTS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF BUSINESSDRIVERDEPARTMENTS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_BUSINESSDRIVERDEPARTMENTS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
BUSINESSDRIVERDEPARTMENTS_KEY
, SNAPSHOT_WEEK_KEY
,BUSINESSDRIVERID
, DEPARTMENTID
, BUSINESSDRIVERNAME
, DEPARTMENTNAME
, LINKEDBUSINESSDRIVER
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_BUSINESSDRIVERDEPARTMENTS_WEEKLY_SNAPSHOT')}}  
