--[   NPD_MSPROJECTS_PROJECTS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF PROJECTS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_PROJECTS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
PROJECTS_KEY
, SNAPSHOT_WEEK_KEY
,PROJECTID
, AGILE
, BUSINESSUNIT
, CSAGILE , CONVERT_TIMEZONE('UTC','America/Phoenix',CSAGILE) AS BIW_CSAGILE_MST
, DIVISIONPRIORITY
, ENGRPRODOWNER
, ENTERPRISEPROJECTTYPEDESCRIPTION
, ENTERPRISEPROJECTTYPEID
, ENTERPRISEPROJECTTYPEISDEFAULT
, ENTERPRISEPROJECTTYPENAME
, FINANCIAL
, OPTIMIZERCOMMITDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',OPTIMIZERCOMMITDATE) AS BIW_OPTIMIZERCOMMITDATE_MST
, OPTIMIZERDECISIONALIASLOOKUPTABLEID
, OPTIMIZERDECISIONALIASLOOKUPTABLEVALUEID
, OPTIMIZERDECISIONID
, OPTIMIZERDECISIONNAME
, OPTIMIZERSOLUTIONNAME
, OSAGILE
, OTHER
, PARENTPROJECTID
, PLANNERCOMMITDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PLANNERCOMMITDATE) AS BIW_PLANNERCOMMITDATE_MST
, PLANNERDECISIONALIASLOOKUPTABLEID
, PLANNERDECISIONALIASLOOKUPTABLEVALUEID
, PLANNERDECISIONID
, PLANNERDECISIONNAME
, PLANNERENDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PLANNERENDDATE) AS BIW_PLANNERENDDATE_MST
, PLANNERSOLUTIONNAME
, PLANNERSTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PLANNERSTARTDATE) AS BIW_PLANNERSTARTDATE_MST
, PRODMRKTLEAD
, PROJECTACTUALCOST
, PROJECTACTUALDURATION
, PROJECTACTUALFINISHDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTACTUALFINISHDATE) AS BIW_PROJECTACTUALFINISHDATE_MST
, PROJECTACTUALOVERTIMECOST
, PROJECTACTUALOVERTIMEWORK
, PROJECTACTUALREGULARCOST
, PROJECTACTUALREGULARWORK
, PROJECTACTUALSTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTACTUALSTARTDATE) AS BIW_PROJECTACTUALSTARTDATE_MST
, PROJECTACTUALWORK
, PROJECTACWP
, PROJECTAUTHORNAME
, PROJECTBCWP
, PROJECTBCWS
, PROJECTBUDGETCOST
, PROJECTBUDGETWORK
, PROJECTCALCULATIONSARESTALE
, PROJECTCALENDARDURATION
, PROJECTCATEGORYNAME
, PROJECTCOMPANYNAME
, PROJECTCOST
, PROJECTCOSTVARIANCE
, PROJECTCPI
, PROJECTCREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTCREATEDDATE) AS BIW_PROJECTCREATEDDATE_MST
, PROJECTCURRENCY
, PROJECTCV
, PROJECTCVP
, PROJECTDEPARTMENTS
, PROJECTDESCRIPTION
, PROJECTDURATION
, PROJECTDURATIONVARIANCE
, PROJECTEAC
, PROJECTEARLYFINISH , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTEARLYFINISH) AS BIW_PROJECTEARLYFINISH_MST
, PROJECTEARLYSTART , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTEARLYSTART) AS BIW_PROJECTEARLYSTART_MST
, PROJECTEARNEDVALUEISSTALE
, PROJECTENTERPRISEFEATURES
, PROJECTFINISHDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTFINISHDATE) AS BIW_PROJECTFINISHDATE_MST
, PROJECTFINISHVARIANCE
, PROJECTFIXEDCOST
, PROJECTIDENTIFIER
, PROJECTKEYWORDS
, PROJECTLASTPUBLISHEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTLASTPUBLISHEDDATE) AS BIW_PROJECTLASTPUBLISHEDDATE_MST
, PROJECTLATEFINISH , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTLATEFINISH) AS BIW_PROJECTLATEFINISH_MST
, PROJECTLATESTART , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTLATESTART) AS BIW_PROJECTLATESTART_MST
, PROJECTMANAGERNAME
, PROJECTMODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTMODIFIEDDATE) AS BIW_PROJECTMODIFIEDDATE_MST
, PROJECTNAME
, PROJECTOVERTIMECOST
, PROJECTOVERTIMEWORK
, PROJECTOWNERID
, PROJECTOWNERNAME
, PROJECTPERCENTCOMPLETED
, PROJECTPERCENTWORKCOMPLETED
, PROJECTREGULARCOST
, PROJECTREGULARWORK
, PROJECTREMAININGCOST
, PROJECTREMAININGDURATION
, PROJECTREMAININGOVERTIMECOST
, PROJECTREMAININGOVERTIMEWORK
, PROJECTREMAININGREGULARCOST
, PROJECTREMAININGREGULARWORK
, PROJECTREMAININGWORK
, PROJECTRESOURCEPLANWORK
, PROJECTSPI
, PROJECTSTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTSTARTDATE) AS BIW_PROJECTSTARTDATE_MST
, PROJECTSTARTVARIANCE
, PROJECTSTATUSDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROJECTSTATUSDATE) AS BIW_PROJECTSTATUSDATE_MST
, PROJECTSUBJECT
, PROJECTSV
, PROJECTSVP
, PROJECTTCPI
, PROJECTTIMEPHASED
, PROJECTTITLE
, PROJECTTYPE
, PROJECTVAC
, PROJECTWORK
, PROJECTWORKSPACEINTERNALURL
, PROJECTWORKVARIANCE
, RESOURCE
, RESOURCEPLANUTILIZATIONDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',RESOURCEPLANUTILIZATIONDATE) AS BIW_RESOURCEPLANUTILIZATIONDATE_MST
, RESOURCEPLANUTILIZATIONTYPE
, SCHEDULE
, SPEC
, STATUSCOMMENTS
, TOPPROJECT
, WORKFLOWCREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',WORKFLOWCREATEDDATE) AS BIW_WORKFLOWCREATEDDATE_MST
, WORKFLOWERROR
, WORKFLOWERRORRESPONSECODE
, WORKFLOWINSTANCEID
, WORKFLOWOWNERID
, WORKFLOWOWNERNAME
, LINKEDASSIGNMENTBASELINES
, LINKEDASSIGNMENTS
, LINKEDDELIVERABLES
, LINKEDDEPENDENCIES
, LINKEDISSUES
, LINKEDRISKS
, LINKEDSTAGESINFO
, LINKEDTASKS
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_PROJECTS_WEEKLY_SNAPSHOT')}}  
