--[   NPD_MSPROJECTS_TASKBASELINETIMEPHASEDDATASET_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF TASKBASELINETIMEPHASEDDATASET ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_TASKBASELINETIMEPHASEDDATASET_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
TASKBASELINETIMEPHASEDDATASET_KEY
, SNAPSHOT_WEEK_KEY
,BASELINENUMBER
, PROJECTID
, TASKID
, TIMEBYDAY , CONVERT_TIMEZONE('UTC','America/Phoenix',TIMEBYDAY) AS BIW_TIMEBYDAY_MST
, FISCALPERIODID
, PROJECTNAME
, TASKBASELINEBUDGETCOST
, TASKBASELINEBUDGETWORK
, TASKBASELINECOST
, TASKBASELINEFIXEDCOST
, TASKBASELINEMODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKBASELINEMODIFIEDDATE) AS BIW_TASKBASELINEMODIFIEDDATE_MST
, TASKBASELINEWORK
, TASKNAME
, LINKEDPROJECT
, LINKEDTASK
, LINKEDTASKBASELINES
, LINKEDTIME
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_TASKBASELINETIMEPHASEDDATASET_WEEKLY_SNAPSHOT')}}  
