--[   NPD_MSPROJECTS_TIMESHEETS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF TIMESHEETS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_TIMESHEETS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
TIMESHEETS_KEY
, SNAPSHOT_WEEK_KEY
,TIMESHEETID
, COMMENT
, DESCRIPTION
, ENDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',ENDDATE) AS BIW_ENDDATE_MST
, MODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',MODIFIEDDATE) AS BIW_MODIFIEDDATE_MST
, PERIODID
, PERIODNAME
, PERIODSTATUSID
, STARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',STARTDATE) AS BIW_STARTDATE_MST
, STATUSDESCRIPTION
, TIMESHEETNAME
, TIMESHEETOWNER
, TIMESHEETOWNERID
, TIMESHEETSTATUSID
, LINKEDLINES
, LINKEDPERIODS
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_TIMESHEETS_WEEKLY_SNAPSHOT')}}  
