--[   NPD_MSPROJECTS_ENGAGEMENTSCOMMENTS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF ENGAGEMENTSCOMMENTS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_ENGAGEMENTSCOMMENTS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
ENGAGEMENTSCOMMENTS_KEY
, SNAPSHOT_WEEK_KEY
,COMMENTID
, AUTHORID
, AUTHORNAME
, COMMENTCREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',COMMENTCREATEDDATE) AS BIW_COMMENTCREATEDDATE_MST
, COMMENTMESSAGE
, ENGAGEMENTID
, ENGAGEMENTNAME
, LINKEDENGAGEMENT
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_ENGAGEMENTSCOMMENTS_WEEKLY_SNAPSHOT')}}  
