/*---------------------------------------------------------------------------
Command to run model:
-- dbt run --select ODS_NPD_MSPROJECTS_ASSIGNMENTS_WEEKLY_SNAPSHOT
-- dbt build --full-refresh --select ODS_NPD_MSPROJECTS_ASSIGNMENTS_WEEKLY_SNAPSHOT

Version     Date            Author              Description
-------     --------        -----------         ----------------------------------
1.0         25-JAN-2023     KALI DANDAPANI      Initial Version
---------------------------------------------------------------------------*/

{################# EDW Job Template Variables #################}
{%-set v_pk_list = ['ASSIGNMENTS_KEY']-%}

{################# Batch control insert and update SQL #################}
{%- set v_dbt_job_name = 'DBT_ODS_NPD_MSPROJECTS_ASSIGNMENTS_WEEKLY_SNAPSHOT'-%}
-- Step 1 Batch process info
{%- set v_watermark = edw_batch_control(v_dbt_job_name,config.get('schema'),config.get('alias') ,config.get('tags'),config.get('materialized') ) -%}
{%- set V_LWM = v_watermark[0] -%}
{%- set V_HWM = v_watermark[1] -%}
{%- set V_START_DTTM = v_watermark[2] -%}
{%- set V_BIW_BATCH_ID = v_watermark[3] -%}
{%- set v_sql_upd_success_batch = "CALL UTILITY.EDW_BATCH_SUCCESS_PROC('"~v_dbt_job_name~"')" -%}

{################# Snowflake Object Configuration #################}
{{
    config(
         description = 'Building ODS table ASSIGNMENTS_WEEKLY_SNAPSHOT for NPD LANDING PROJECT'
        ,transient=false   
         ,materialized='incremental'
        ,schema ='ODS_NPD'
        ,alias= 'MSPROJECTS_ASSIGNMENTS_WEEKLY_SNAPSHOT'
        ,tags =['ODS_NPD']
        ,merge_update_columns = ['ASSIGNMENTID','PROJECTID','ASSIGNMENTACTUALCOST','ASSIGNMENTACTUALFINISHDATE','ASSIGNMENTACTUALOVERTIMECOST','ASSIGNMENTACTUALOVERTIMEWORK','ASSIGNMENTACTUALREGULARCOST','ASSIGNMENTACTUALREGULARWORK','ASSIGNMENTACTUALSTARTDATE','ASSIGNMENTACTUALWORK','ASSIGNMENTACWP','ASSIGNMENTALLUPDATESAPPLIED','ASSIGNMENTBCWP','ASSIGNMENTBCWS','ASSIGNMENTBOOKINGDESCRIPTION','ASSIGNMENTBOOKINGID','ASSIGNMENTBOOKINGNAME','ASSIGNMENTBUDGETCOST','ASSIGNMENTBUDGETMATERIALWORK','ASSIGNMENTBUDGETWORK','ASSIGNMENTCOST','ASSIGNMENTCOSTVARIANCE','ASSIGNMENTCREATEDDATE','ASSIGNMENTCREATEDREVISIONCOUNTER','ASSIGNMENTCV','ASSIGNMENTDELAY','ASSIGNMENTFINISHDATE','ASSIGNMENTFINISHVARIANCE','ASSIGNMENTISOVERALLOCATED','ASSIGNMENTISPUBLISHED','ASSIGNMENTMATERIALACTUALWORK','ASSIGNMENTMATERIALWORK','ASSIGNMENTMODIFIEDDATE','ASSIGNMENTMODIFIEDREVISIONCOUNTER','ASSIGNMENTOVERTIMECOST','ASSIGNMENTOVERTIMEWORK','ASSIGNMENTPEAKUNITS','ASSIGNMENTPERCENTWORKCOMPLETED','ASSIGNMENTREGULARCOST','ASSIGNMENTREGULARWORK','ASSIGNMENTREMAININGCOST','ASSIGNMENTREMAININGOVERTIMECOST','ASSIGNMENTREMAININGOVERTIMEWORK','ASSIGNMENTREMAININGREGULARCOST','ASSIGNMENTREMAININGREGULARWORK','ASSIGNMENTREMAININGWORK','ASSIGNMENTRESOURCEPLANWORK','ASSIGNMENTRESOURCETYPE','ASSIGNMENTSTARTDATE','ASSIGNMENTSTARTVARIANCE','ASSIGNMENTSV','ASSIGNMENTTYPE','ASSIGNMENTUPDATESAPPLIEDDATE','ASSIGNMENTVAC','ASSIGNMENTWORK','ASSIGNMENTWORKVARIANCE','COSTTYPE_R','DETECTABILITY_T','FLAGSTATUS_T','HEALTH_T','IMPACT_T','ISPUBLIC','MITIGATIONFLAG_T','NPDGATE_T','NPDMILESTONE_T','PROBABILITY_T','PROJECTNAME','RBS_R','RESOURCEDEPARTMENTS_R','RESOURCEID','RESOURCENAME','RISKFLAG_T','RISKLEVEL_T','RISKSCORE_T','RISK_T','ROLE_R','TASKID','TASKISACTIVE','TASKNAME','TIMESHEETCLASSID','TYPEDESCRIPTION','TYPENAME','LINKEDBASELINE','LINKEDPROJECT','LINKEDRESOURCE','LINKEDTASK','LINKEDTIMEPHASEDDATA','BIW_UPD_DTTM','BIW_BATCH_ID','BIW_MD5_KEY']
        ,unique_key= v_pk_list
        ,post_hook= [v_sql_upd_success_batch]	
        )
}}

SELECT 
STG.ASSIGNMENTS_KEY
,STG.SNAPSHOT_WEEK_KEY
,STG.ASSIGNMENTID
,STG.PROJECTID
,STG.ASSIGNMENTACTUALCOST
,STG.ASSIGNMENTACTUALFINISHDATE
,STG.ASSIGNMENTACTUALOVERTIMECOST
,STG.ASSIGNMENTACTUALOVERTIMEWORK
,STG.ASSIGNMENTACTUALREGULARCOST
,STG.ASSIGNMENTACTUALREGULARWORK
,STG.ASSIGNMENTACTUALSTARTDATE
,STG.ASSIGNMENTACTUALWORK
,STG.ASSIGNMENTACWP
,STG.ASSIGNMENTALLUPDATESAPPLIED
,STG.ASSIGNMENTBCWP
,STG.ASSIGNMENTBCWS
,STG.ASSIGNMENTBOOKINGDESCRIPTION
,STG.ASSIGNMENTBOOKINGID
,STG.ASSIGNMENTBOOKINGNAME
,STG.ASSIGNMENTBUDGETCOST
,STG.ASSIGNMENTBUDGETMATERIALWORK
,STG.ASSIGNMENTBUDGETWORK
,STG.ASSIGNMENTCOST
,STG.ASSIGNMENTCOSTVARIANCE
,STG.ASSIGNMENTCREATEDDATE
,STG.ASSIGNMENTCREATEDREVISIONCOUNTER
,STG.ASSIGNMENTCV
,STG.ASSIGNMENTDELAY
,STG.ASSIGNMENTFINISHDATE
,STG.ASSIGNMENTFINISHVARIANCE
,STG.ASSIGNMENTISOVERALLOCATED
,STG.ASSIGNMENTISPUBLISHED
,STG.ASSIGNMENTMATERIALACTUALWORK
,STG.ASSIGNMENTMATERIALWORK
,STG.ASSIGNMENTMODIFIEDDATE
,STG.ASSIGNMENTMODIFIEDREVISIONCOUNTER
,STG.ASSIGNMENTOVERTIMECOST
,STG.ASSIGNMENTOVERTIMEWORK
,STG.ASSIGNMENTPEAKUNITS
,STG.ASSIGNMENTPERCENTWORKCOMPLETED
,STG.ASSIGNMENTREGULARCOST
,STG.ASSIGNMENTREGULARWORK
,STG.ASSIGNMENTREMAININGCOST
,STG.ASSIGNMENTREMAININGOVERTIMECOST
,STG.ASSIGNMENTREMAININGOVERTIMEWORK
,STG.ASSIGNMENTREMAININGREGULARCOST
,STG.ASSIGNMENTREMAININGREGULARWORK
,STG.ASSIGNMENTREMAININGWORK
,STG.ASSIGNMENTRESOURCEPLANWORK
,STG.ASSIGNMENTRESOURCETYPE
,STG.ASSIGNMENTSTARTDATE
,STG.ASSIGNMENTSTARTVARIANCE
,STG.ASSIGNMENTSV
,STG.ASSIGNMENTTYPE
,STG.ASSIGNMENTUPDATESAPPLIEDDATE
,STG.ASSIGNMENTVAC
,STG.ASSIGNMENTWORK
,STG.ASSIGNMENTWORKVARIANCE
,STG.COSTTYPE_R
,STG.DETECTABILITY_T
,STG.FLAGSTATUS_T
,STG.HEALTH_T
,STG.IMPACT_T
,STG.ISPUBLIC
,STG.MITIGATIONFLAG_T
,STG.NPDGATE_T
,STG.NPDMILESTONE_T
,STG.PROBABILITY_T
,STG.PROJECTNAME
,STG.RBS_R
,STG.RESOURCEDEPARTMENTS_R
,STG.RESOURCEID
,STG.RESOURCENAME
,STG.RISKFLAG_T
,STG.RISKLEVEL_T
,STG.RISKSCORE_T
,STG.RISK_T
,STG.ROLE_R
,STG.TASKID
,STG.TASKISACTIVE
,STG.TASKNAME
,STG.TIMESHEETCLASSID
,STG.TYPEDESCRIPTION
,STG.TYPENAME
,STG.LINKEDBASELINE
,STG.LINKEDPROJECT
,STG.LINKEDRESOURCE
,STG.LINKEDTASK
,STG.LINKEDTIMEPHASEDDATA
,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_INS_DTTM 
    ,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_UPD_DTTM 
   ,{{V_BIW_BATCH_ID}}::NUMBER as BIW_BATCH_ID ,STG.BIW_MD5_KEY
    FROM 
        {{ref ('ETL_ODS_NPD_MSPROJECTS_ASSIGNMENTS_WEEKLY_SNAPSHOT')}}  STG  
{% if is_incremental() %}
  LEFT JOIN {{ this }} TGT
  on STG.ASSIGNMENTS_KEY= TGT.ASSIGNMENTS_KEY
  WHERE TGT.BIW_MD5_KEY<>STG.BIW_MD5_KEY OR TGT.BIW_MD5_KEY IS NULL
{% endif %}
