
/*---------------------------------------------------------------------------
Command to run model:
-- dbt run --select ETL_ODS_NPD_MSPROJECTS_PROJECTS_WEEKLY_SNAPSHOT 
-- dbt build --full-refresh --select ETL_ODS_NPD_MSPROJECTS_PROJECTS_WEEKLY_SNAPSHOT 

Version     Date            Author              Description
-------     --------        -----------         ----------------------------------
1.0         25-JAN-2023     KALI DANDAPANI      Initial Version
---------------------------------------------------------------------------*/

{################# EDW Job Template Variables #################}
{%-set v_pk_list = ['PROJECTID']-%}

{################# Batch control insert and update SQL #################}
{%- set v_dbt_job_name = 'DBT_ETL_ODS_NPD_MSPROJECTS_PROJECTS_WEEKLY_SNAPSHOT'-%}
-- Step 1 Batch process info
{%- set v_watermark = edw_batch_control(v_dbt_job_name,config.get('schema'),config.get('alias') ,config.get('tags'),config.get('materialized') ) -%}
{%- set V_LWM = v_watermark[0] -%}
{%- set V_HWM = v_watermark[1] -%}
{%- set V_START_DTTM = v_watermark[2] -%}
{%- set V_BIW_BATCH_ID = v_watermark[3] -%}
{%- set v_sql_upd_success_batch = "CALL UTILITY.EDW_BATCH_SUCCESS_PROC('"~v_dbt_job_name~"')" -%}

{################# Snowflake Object Configuration #################}
{{
    config(
         description = 'Building ETL table PROJECTS_WEEKLY_SNAPSHOT for NPD LANDING PROJECT'
        ,transient=true   
        ,materialized='table'
        ,schema ='ETL_ODS_NPD'
        ,alias= 'MSPROJECTS_PROJECTS_WEEKLY_SNAPSHOT'
        ,tags =['ODS_NPD']
        ,post_hook= [v_sql_upd_success_batch]	
        )
}}

WITH FISCAL_WEEK AS 
(
    SELECT 
        DISTINCT FISCAL_WEEK_KEY
    FROM 
    {{ref('MART_DATE') }}
    WHERE 
        CALENDAR_DATE = (CURRENT_TIMESTAMP() - INTERVAL '7 HOUR')::DATE
        or CALENDAR_DATE = (CURRENT_TIMESTAMP() )::DATE
)

,PROJECTS AS (
SELECT PROJECTID
, AGILE
, BUSINESSUNIT
, CSAGILE
, DIVISIONPRIORITY
, ENGRPRODOWNER
, ENTERPRISEPROJECTTYPEDESCRIPTION
, ENTERPRISEPROJECTTYPEID
, ENTERPRISEPROJECTTYPEISDEFAULT
, ENTERPRISEPROJECTTYPENAME
, FINANCIAL
, OPTIMIZERCOMMITDATE
, OPTIMIZERDECISIONALIASLOOKUPTABLEID
, OPTIMIZERDECISIONALIASLOOKUPTABLEVALUEID
, OPTIMIZERDECISIONID
, OPTIMIZERDECISIONNAME
, OPTIMIZERSOLUTIONNAME
, OSAGILE
, OTHER
, PARENTPROJECTID
, PLANNERCOMMITDATE
, PLANNERDECISIONALIASLOOKUPTABLEID
, PLANNERDECISIONALIASLOOKUPTABLEVALUEID
, PLANNERDECISIONID
, PLANNERDECISIONNAME
, PLANNERENDDATE
, PLANNERSOLUTIONNAME
, PLANNERSTARTDATE
, PRODMRKTLEAD
, PROJECTACTUALCOST
, PROJECTACTUALDURATION
, PROJECTACTUALFINISHDATE
, PROJECTACTUALOVERTIMECOST
, PROJECTACTUALOVERTIMEWORK
, PROJECTACTUALREGULARCOST
, PROJECTACTUALREGULARWORK
, PROJECTACTUALSTARTDATE
, PROJECTACTUALWORK
, PROJECTACWP
, PROJECTAUTHORNAME
, PROJECTBCWP
, PROJECTBCWS
, PROJECTBUDGETCOST
, PROJECTBUDGETWORK
, PROJECTCALCULATIONSARESTALE
, PROJECTCALENDARDURATION
, PROJECTCATEGORYNAME
, PROJECTCOMPANYNAME
, PROJECTCOST
, PROJECTCOSTVARIANCE
, PROJECTCPI
, PROJECTCREATEDDATE
, PROJECTCURRENCY
, PROJECTCV
, PROJECTCVP
, PROJECTDEPARTMENTS
, PROJECTDESCRIPTION
, PROJECTDURATION
, PROJECTDURATIONVARIANCE
, PROJECTEAC
, PROJECTEARLYFINISH
, PROJECTEARLYSTART
, PROJECTEARNEDVALUEISSTALE
, PROJECTENTERPRISEFEATURES
, PROJECTFINISHDATE
, PROJECTFINISHVARIANCE
, PROJECTFIXEDCOST
, PROJECTIDENTIFIER
, PROJECTKEYWORDS
, PROJECTLASTPUBLISHEDDATE
, PROJECTLATEFINISH
, PROJECTLATESTART
, PROJECTMANAGERNAME
, PROJECTMODIFIEDDATE
, PROJECTNAME
, PROJECTOVERTIMECOST
, PROJECTOVERTIMEWORK
, PROJECTOWNERID
, PROJECTOWNERNAME
, PROJECTPERCENTCOMPLETED
, PROJECTPERCENTWORKCOMPLETED
, PROJECTREGULARCOST
, PROJECTREGULARWORK
, PROJECTREMAININGCOST
, PROJECTREMAININGDURATION
, PROJECTREMAININGOVERTIMECOST
, PROJECTREMAININGOVERTIMEWORK
, PROJECTREMAININGREGULARCOST
, PROJECTREMAININGREGULARWORK
, PROJECTREMAININGWORK
, PROJECTRESOURCEPLANWORK
, PROJECTSPI
, PROJECTSTARTDATE
, PROJECTSTARTVARIANCE
, PROJECTSTATUSDATE
, PROJECTSUBJECT
, PROJECTSV
, PROJECTSVP
, PROJECTTCPI
, PROJECTTIMEPHASED
, PROJECTTITLE
, PROJECTTYPE
, PROJECTVAC
, PROJECTWORK
, PROJECTWORKSPACEINTERNALURL
, PROJECTWORKVARIANCE
, RESOURCE
, RESOURCEPLANUTILIZATIONDATE
, RESOURCEPLANUTILIZATIONTYPE
, SCHEDULE
, SPEC
, STATUSCOMMENTS
, TOPPROJECT
, WORKFLOWCREATEDDATE
, WORKFLOWERROR
, WORKFLOWERRORRESPONSECODE
, WORKFLOWINSTANCEID
, WORKFLOWOWNERID
, WORKFLOWOWNERNAME
, LINKEDASSIGNMENTBASELINES
, LINKEDASSIGNMENTS
, LINKEDDELIVERABLES
, LINKEDDEPENDENCIES
, LINKEDISSUES
, LINKEDRISKS
, LINKEDSTAGESINFO
, LINKEDTASKS
, BIW_INS_DTTM
, BIW_UPD_DTTM
FROM 
    {{source ('STG_NPD_MSPROJECTS_ODATAV1','PROJECTS')}}  
    QUALIFY( ROW_NUMBER() OVER (PARTITION BY PROJECTID  ORDER BY BIW_UPD_DTTM DESC) =1)
)

SELECT 
    MD5(OBJECT_CONSTRUCT (  'COL1',FSC_WK.FISCAL_WEEK_KEY::STRING
                            ,'COL2',STG.PROJECTID::STRING
                         )::STRING 
        )::BINARY AS PROJECTS_KEY 
    ,FSC_WK.FISCAL_WEEK_KEY AS SNAPSHOT_WEEK_KEY
    ,PROJECTID
, STG.AGILE
, STG.BUSINESSUNIT
, STG.CSAGILE
, STG.DIVISIONPRIORITY
, STG.ENGRPRODOWNER
, STG.ENTERPRISEPROJECTTYPEDESCRIPTION
, STG.ENTERPRISEPROJECTTYPEID
, STG.ENTERPRISEPROJECTTYPEISDEFAULT
, STG.ENTERPRISEPROJECTTYPENAME
, STG.FINANCIAL
, STG.OPTIMIZERCOMMITDATE
, STG.OPTIMIZERDECISIONALIASLOOKUPTABLEID
, STG.OPTIMIZERDECISIONALIASLOOKUPTABLEVALUEID
, STG.OPTIMIZERDECISIONID
, STG.OPTIMIZERDECISIONNAME
, STG.OPTIMIZERSOLUTIONNAME
, STG.OSAGILE
, STG.OTHER
, STG.PARENTPROJECTID
, STG.PLANNERCOMMITDATE
, STG.PLANNERDECISIONALIASLOOKUPTABLEID
, STG.PLANNERDECISIONALIASLOOKUPTABLEVALUEID
, STG.PLANNERDECISIONID
, STG.PLANNERDECISIONNAME
, STG.PLANNERENDDATE
, STG.PLANNERSOLUTIONNAME
, STG.PLANNERSTARTDATE
, STG.PRODMRKTLEAD
, STG.PROJECTACTUALCOST
, STG.PROJECTACTUALDURATION
, STG.PROJECTACTUALFINISHDATE
, STG.PROJECTACTUALOVERTIMECOST
, STG.PROJECTACTUALOVERTIMEWORK
, STG.PROJECTACTUALREGULARCOST
, STG.PROJECTACTUALREGULARWORK
, STG.PROJECTACTUALSTARTDATE
, STG.PROJECTACTUALWORK
, STG.PROJECTACWP
, STG.PROJECTAUTHORNAME
, STG.PROJECTBCWP
, STG.PROJECTBCWS
, STG.PROJECTBUDGETCOST
, STG.PROJECTBUDGETWORK
, STG.PROJECTCALCULATIONSARESTALE
, STG.PROJECTCALENDARDURATION
, STG.PROJECTCATEGORYNAME
, STG.PROJECTCOMPANYNAME
, STG.PROJECTCOST
, STG.PROJECTCOSTVARIANCE
, STG.PROJECTCPI
, STG.PROJECTCREATEDDATE
, STG.PROJECTCURRENCY
, STG.PROJECTCV
, STG.PROJECTCVP
, STG.PROJECTDEPARTMENTS
, STG.PROJECTDESCRIPTION
, STG.PROJECTDURATION
, STG.PROJECTDURATIONVARIANCE
, STG.PROJECTEAC
, STG.PROJECTEARLYFINISH
, STG.PROJECTEARLYSTART
, STG.PROJECTEARNEDVALUEISSTALE
, STG.PROJECTENTERPRISEFEATURES
, STG.PROJECTFINISHDATE
, STG.PROJECTFINISHVARIANCE
, STG.PROJECTFIXEDCOST
, STG.PROJECTIDENTIFIER
, STG.PROJECTKEYWORDS
, STG.PROJECTLASTPUBLISHEDDATE
, STG.PROJECTLATEFINISH
, STG.PROJECTLATESTART
, STG.PROJECTMANAGERNAME
, STG.PROJECTMODIFIEDDATE
, STG.PROJECTNAME
, STG.PROJECTOVERTIMECOST
, STG.PROJECTOVERTIMEWORK
, STG.PROJECTOWNERID
, STG.PROJECTOWNERNAME
, STG.PROJECTPERCENTCOMPLETED
, STG.PROJECTPERCENTWORKCOMPLETED
, STG.PROJECTREGULARCOST
, STG.PROJECTREGULARWORK
, STG.PROJECTREMAININGCOST
, STG.PROJECTREMAININGDURATION
, STG.PROJECTREMAININGOVERTIMECOST
, STG.PROJECTREMAININGOVERTIMEWORK
, STG.PROJECTREMAININGREGULARCOST
, STG.PROJECTREMAININGREGULARWORK
, STG.PROJECTREMAININGWORK
, STG.PROJECTRESOURCEPLANWORK
, STG.PROJECTSPI
, STG.PROJECTSTARTDATE
, STG.PROJECTSTARTVARIANCE
, STG.PROJECTSTATUSDATE
, STG.PROJECTSUBJECT
, STG.PROJECTSV
, STG.PROJECTSVP
, STG.PROJECTTCPI
, STG.PROJECTTIMEPHASED
, STG.PROJECTTITLE
, STG.PROJECTTYPE
, STG.PROJECTVAC
, STG.PROJECTWORK
, STG.PROJECTWORKSPACEINTERNALURL
, STG.PROJECTWORKVARIANCE
, STG.RESOURCE
, STG.RESOURCEPLANUTILIZATIONDATE
, STG.RESOURCEPLANUTILIZATIONTYPE
, STG.SCHEDULE
, STG.SPEC
, STG.STATUSCOMMENTS
, STG.TOPPROJECT
, STG.WORKFLOWCREATEDDATE
, STG.WORKFLOWERROR
, STG.WORKFLOWERRORRESPONSECODE
, STG.WORKFLOWINSTANCEID
, STG.WORKFLOWOWNERID
, STG.WORKFLOWOWNERNAME
, STG.LINKEDASSIGNMENTBASELINES
, STG.LINKEDASSIGNMENTS
, STG.LINKEDDELIVERABLES
, STG.LINKEDDEPENDENCIES
, STG.LINKEDISSUES
, STG.LINKEDRISKS
, STG.LINKEDSTAGESINFO
,STG.LINKEDTASKS
,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_INS_DTTM 
    ,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_UPD_DTTM 
   ,{{V_BIW_BATCH_ID}}::NUMBER as BIW_BATCH_ID 
   ,md5(object_construct ('COL1',PROJECTID::string ,'COL2',AGILE::string ,'COL3',BUSINESSUNIT::string ,'COL4',CSAGILE::string ,'COL5',DIVISIONPRIORITY::string ,'COL6',ENGRPRODOWNER::string ,'COL7',ENTERPRISEPROJECTTYPEDESCRIPTION::string ,'COL8',ENTERPRISEPROJECTTYPEID::string ,'COL9',ENTERPRISEPROJECTTYPEISDEFAULT::string ,'COL10',ENTERPRISEPROJECTTYPENAME::string ,'COL11',FINANCIAL::string ,'COL12',OPTIMIZERCOMMITDATE::string ,'COL13',OPTIMIZERDECISIONALIASLOOKUPTABLEID::string ,'COL14',OPTIMIZERDECISIONALIASLOOKUPTABLEVALUEID::string ,'COL15',OPTIMIZERDECISIONID::string ,'COL16',OPTIMIZERDECISIONNAME::string ,'COL17',OPTIMIZERSOLUTIONNAME::string ,'COL18',OSAGILE::string ,'COL19',OTHER::string ,'COL20',PARENTPROJECTID::string ,'COL21',PLANNERCOMMITDATE::string ,'COL22',PLANNERDECISIONALIASLOOKUPTABLEID::string ,'COL23',PLANNERDECISIONALIASLOOKUPTABLEVALUEID::string ,'COL24',PLANNERDECISIONID::string ,'COL25',PLANNERDECISIONNAME::string ,'COL26',PLANNERENDDATE::string ,'COL27',PLANNERSOLUTIONNAME::string ,'COL28',PLANNERSTARTDATE::string ,'COL29',PRODMRKTLEAD::string ,'COL30',PROJECTACTUALCOST::string ,'COL31',PROJECTACTUALDURATION::string ,'COL32',PROJECTACTUALFINISHDATE::string ,'COL33',PROJECTACTUALOVERTIMECOST::string ,'COL34',PROJECTACTUALOVERTIMEWORK::string ,'COL35',PROJECTACTUALREGULARCOST::string ,'COL36',PROJECTACTUALREGULARWORK::string ,'COL37',PROJECTACTUALSTARTDATE::string ,'COL38',PROJECTACTUALWORK::string ,'COL39',PROJECTACWP::string ,'COL40',PROJECTAUTHORNAME::string ,'COL41',PROJECTBCWP::string ,'COL42',PROJECTBCWS::string ,'COL43',PROJECTBUDGETCOST::string ,'COL44',PROJECTBUDGETWORK::string ,'COL45',PROJECTCALCULATIONSARESTALE::string ,'COL46',PROJECTCALENDARDURATION::string ,'COL47',PROJECTCATEGORYNAME::string ,'COL48',PROJECTCOMPANYNAME::string ,'COL49',PROJECTCOST::string ,'COL50',PROJECTCOSTVARIANCE::string ,'COL51',PROJECTCPI::string ,'COL52',PROJECTCREATEDDATE::string ,'COL53',PROJECTCURRENCY::string ,'COL54',PROJECTCV::string ,'COL55',PROJECTCVP::string ,'COL56',PROJECTDEPARTMENTS::string ,'COL57',PROJECTDESCRIPTION::string ,'COL58',PROJECTDURATION::string ,'COL59',PROJECTDURATIONVARIANCE::string ,'COL60',PROJECTEAC::string ,'COL61',PROJECTEARLYFINISH::string ,'COL62',PROJECTEARLYSTART::string ,'COL63',PROJECTEARNEDVALUEISSTALE::string ,'COL64',PROJECTENTERPRISEFEATURES::string ,'COL65',PROJECTFINISHDATE::string ,'COL66',PROJECTFINISHVARIANCE::string ,'COL67',PROJECTFIXEDCOST::string ,'COL68',PROJECTIDENTIFIER::string ,'COL69',PROJECTKEYWORDS::string ,'COL70',PROJECTLASTPUBLISHEDDATE::string ,'COL71',PROJECTLATEFINISH::string ,'COL72',PROJECTLATESTART::string ,'COL73',PROJECTMANAGERNAME::string ,'COL74',PROJECTMODIFIEDDATE::string ,'COL75',PROJECTNAME::string ,'COL76',PROJECTOVERTIMECOST::string ,'COL77',PROJECTOVERTIMEWORK::string ,'COL78',PROJECTOWNERID::string ,'COL79',PROJECTOWNERNAME::string ,'COL80',PROJECTPERCENTCOMPLETED::string ,'COL81',PROJECTPERCENTWORKCOMPLETED::string ,'COL82',PROJECTREGULARCOST::string ,'COL83',PROJECTREGULARWORK::string ,'COL84',PROJECTREMAININGCOST::string ,'COL85',PROJECTREMAININGDURATION::string ,'COL86',PROJECTREMAININGOVERTIMECOST::string ,'COL87',PROJECTREMAININGOVERTIMEWORK::string ,'COL88',PROJECTREMAININGREGULARCOST::string ,'COL89',PROJECTREMAININGREGULARWORK::string ,'COL90',PROJECTREMAININGWORK::string ,'COL91',PROJECTRESOURCEPLANWORK::string ,'COL92',PROJECTSPI::string ,'COL93',PROJECTSTARTDATE::string ,'COL94',PROJECTSTARTVARIANCE::string ,'COL95',PROJECTSTATUSDATE::string ,'COL96',PROJECTSUBJECT::string ,'COL97',PROJECTSV::string ,'COL98',PROJECTSVP::string ,'COL99',PROJECTTCPI::string ,'COL100',PROJECTTIMEPHASED::string ,'COL101',PROJECTTITLE::string ,'COL102',PROJECTTYPE::string ,'COL103',PROJECTVAC::string ,'COL104',PROJECTWORK::string ,'COL105',PROJECTWORKSPACEINTERNALURL::string ,'COL106',PROJECTWORKVARIANCE::string ,'COL107',RESOURCE::string ,'COL108',RESOURCEPLANUTILIZATIONDATE::string ,'COL109',RESOURCEPLANUTILIZATIONTYPE::string ,'COL110',SCHEDULE::string ,'COL111',SPEC::string ,'COL112',STATUSCOMMENTS::string ,'COL113',TOPPROJECT::string ,'COL114',WORKFLOWCREATEDDATE::string ,'COL115',WORKFLOWERROR::string ,'COL116',WORKFLOWERRORRESPONSECODE::string ,'COL117',WORKFLOWINSTANCEID::string ,'COL118',WORKFLOWOWNERID::string ,'COL119',WORKFLOWOWNERNAME::string ,'COL120',LINKEDASSIGNMENTBASELINES::string ,'COL121',LINKEDASSIGNMENTS::string ,'COL122',LINKEDDELIVERABLES::string ,'COL123',LINKEDDEPENDENCIES::string ,'COL124',LINKEDISSUES::string ,'COL125',LINKEDRISKS::string ,'COL126',LINKEDSTAGESINFO::string ,'COL127',LINKEDTASKS::string )::string )::BINARY as BIW_MD5_KEY

FROM     
PROJECTS  STG 

CROSS JOIN FISCAL_WEEK FSC_WK
