/*---------------------------------------------------------------------------
Command to run model:
-- dbt run --select ETL_ODS_NPD_MSPROJECTS_ENGAGEMENTS_WEEKLY_SNAPSHOT 
-- dbt build --full-refresh --select ETL_ODS_NPD_MSPROJECTS_ENGAGEMENTS_WEEKLY_SNAPSHOT 

Version     Date            Author              Description
-------     --------        -----------         ----------------------------------
1.0         25-JAN-2023     KALI DANDAPANI      Initial Version
---------------------------------------------------------------------------*/

{################# EDW Job Template Variables #################}
{%-set v_pk_list = ['ENGAGEMENTID']-%}

{################# Batch control insert and update SQL #################}
{%- set v_dbt_job_name = 'DBT_ETL_ODS_NPD_MSPROJECTS_ENGAGEMENTS_WEEKLY_SNAPSHOT'-%}
-- Step 1 Batch process info
{%- set v_watermark = edw_batch_control(v_dbt_job_name,config.get('schema'),config.get('alias') ,config.get('tags'),config.get('materialized') ) -%}
{%- set V_LWM = v_watermark[0] -%}
{%- set V_HWM = v_watermark[1] -%}
{%- set V_START_DTTM = v_watermark[2] -%}
{%- set V_BIW_BATCH_ID = v_watermark[3] -%}
{%- set v_sql_upd_success_batch = "CALL UTILITY.EDW_BATCH_SUCCESS_PROC('"~v_dbt_job_name~"')" -%}

{################# Snowflake Object Configuration #################}
{{
    config(
         description = 'Building ETL table ENGAGEMENTS_WEEKLY_SNAPSHOT for NPD LANDING PROJECT'
        ,transient=true   
        ,materialized='table'
        ,schema ='ETL_ODS_NPD'
        ,alias= 'MSPROJECTS_ENGAGEMENTS_WEEKLY_SNAPSHOT'
        ,tags =['ODS_NPD']
        ,post_hook= [v_sql_upd_success_batch]	
        )
}}

WITH FISCAL_WEEK AS 
(
    SELECT 
        DISTINCT FISCAL_WEEK_KEY
    FROM 
    {{ref('MART_DATE') }}
    WHERE 
        CALENDAR_DATE = (CURRENT_TIMESTAMP() - INTERVAL '7 HOUR')::DATE
        or CALENDAR_DATE = (CURRENT_TIMESTAMP() )::DATE
)

,ENGAGEMENTS AS (
SELECT ENGAGEMENTID
, COMMITTEDFINISHDATE
, COMMITTEDMAXUNITS
, COMMITTEDSTARTDATE
, COMMITTEDWORK
, ENGAGEMENTCREATEDDATE
, ENGAGEMENTMODIFIEDDATE
, ENGAGEMENTNAME
, ENGAGEMENTREVIEWEDDATE
, ENGAGEMENTSTATUS
, ENGAGEMENTSUBMITTEDDATE
, MODIFIEDBYRESOURCEID
, MODIFIEDBYRESOURCENAME
, PROJECTID
, PROJECTNAME
, PROPOSEDFINISHDATE
, PROPOSEDMAXUNITS
, PROPOSEDSTARTDATE
, PROPOSEDWORK
, RESOURCEID
, RESOURCENAME
, REVIEWEDBYRESOURCEID
, REVIEWEDBYRESOURCENAME
, SUBMITTEDBYRESOURCEID
, SUBMITTEDBYRESOURCENAME
, LINKEDCOMMENT
, LINKEDTIMEPHASEDINFO
, BIW_INS_DTTM
, BIW_UPD_DTTM
FROM 
    {{source ('STG_NPD_MSPROJECTS_ODATAV1','ENGAGEMENTS')}}  
    QUALIFY( ROW_NUMBER() OVER (PARTITION BY ENGAGEMENTID  ORDER BY BIW_UPD_DTTM DESC) =1)
)

SELECT 
    MD5(OBJECT_CONSTRUCT (  'COL1',FSC_WK.FISCAL_WEEK_KEY::STRING
                            ,'COL2',STG.ENGAGEMENTID::STRING
                         )::STRING 
        )::BINARY AS ENGAGEMENTS_KEY 
    ,FSC_WK.FISCAL_WEEK_KEY AS SNAPSHOT_WEEK_KEY
    ,ENGAGEMENTID
, STG.COMMITTEDFINISHDATE
, STG.COMMITTEDMAXUNITS
, STG.COMMITTEDSTARTDATE
, STG.COMMITTEDWORK
, STG.ENGAGEMENTCREATEDDATE
, STG.ENGAGEMENTMODIFIEDDATE
, STG.ENGAGEMENTNAME
, STG.ENGAGEMENTREVIEWEDDATE
, STG.ENGAGEMENTSTATUS
, STG.ENGAGEMENTSUBMITTEDDATE
, STG.MODIFIEDBYRESOURCEID
, STG.MODIFIEDBYRESOURCENAME
, STG.PROJECTID
, STG.PROJECTNAME
, STG.PROPOSEDFINISHDATE
, STG.PROPOSEDMAXUNITS
, STG.PROPOSEDSTARTDATE
, STG.PROPOSEDWORK
, STG.RESOURCEID
, STG.RESOURCENAME
, STG.REVIEWEDBYRESOURCEID
, STG.REVIEWEDBYRESOURCENAME
, STG.SUBMITTEDBYRESOURCEID
, STG.SUBMITTEDBYRESOURCENAME
, STG.LINKEDCOMMENT
,STG.LINKEDTIMEPHASEDINFO
,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_INS_DTTM 
    ,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_UPD_DTTM 
   ,{{V_BIW_BATCH_ID}}::NUMBER as BIW_BATCH_ID 
   ,md5(object_construct ('COL1',ENGAGEMENTID::string ,'COL2',COMMITTEDFINISHDATE::string ,'COL3',COMMITTEDMAXUNITS::string ,'COL4',COMMITTEDSTARTDATE::string ,'COL5',COMMITTEDWORK::string ,'COL6',ENGAGEMENTCREATEDDATE::string ,'COL7',ENGAGEMENTMODIFIEDDATE::string ,'COL8',ENGAGEMENTNAME::string ,'COL9',ENGAGEMENTREVIEWEDDATE::string ,'COL10',ENGAGEMENTSTATUS::string ,'COL11',ENGAGEMENTSUBMITTEDDATE::string ,'COL12',MODIFIEDBYRESOURCEID::string ,'COL13',MODIFIEDBYRESOURCENAME::string ,'COL14',PROJECTID::string ,'COL15',PROJECTNAME::string ,'COL16',PROPOSEDFINISHDATE::string ,'COL17',PROPOSEDMAXUNITS::string ,'COL18',PROPOSEDSTARTDATE::string ,'COL19',PROPOSEDWORK::string ,'COL20',RESOURCEID::string ,'COL21',RESOURCENAME::string ,'COL22',REVIEWEDBYRESOURCEID::string ,'COL23',REVIEWEDBYRESOURCENAME::string ,'COL24',SUBMITTEDBYRESOURCEID::string ,'COL25',SUBMITTEDBYRESOURCENAME::string ,'COL26',LINKEDCOMMENT::string ,'COL27',LINKEDTIMEPHASEDINFO::string )::string )::BINARY as BIW_MD5_KEY

FROM     
ENGAGEMENTS  STG 

CROSS JOIN FISCAL_WEEK FSC_WK
