/*---------------------------------------------------------------------------
Command to run model:
-- dbt run --select ETL_ODS_NPD_MSPROJECTS_PORTFOLIOANALYSES_WEEKLY_SNAPSHOT 
-- dbt build --full-refresh --select ETL_ODS_NPD_MSPROJECTS_PORTFOLIOANALYSES_WEEKLY_SNAPSHOT 

Version     Date            Author              Description
-------     --------        -----------         ----------------------------------
1.0         25-JAN-2023     KALI DANDAPANI      Initial Version
---------------------------------------------------------------------------*/

{################# EDW Job Template Variables #################}
{%-set v_pk_list = ['ANALYSISID']-%}

{################# Batch control insert and update SQL #################}
{%- set v_dbt_job_name = 'DBT_ETL_ODS_NPD_MSPROJECTS_PORTFOLIOANALYSES_WEEKLY_SNAPSHOT'-%}
-- Step 1 Batch process info
{%- set v_watermark = edw_batch_control(v_dbt_job_name,config.get('schema'),config.get('alias') ,config.get('tags'),config.get('materialized') ) -%}
{%- set V_LWM = v_watermark[0] -%}
{%- set V_HWM = v_watermark[1] -%}
{%- set V_START_DTTM = v_watermark[2] -%}
{%- set V_BIW_BATCH_ID = v_watermark[3] -%}
{%- set v_sql_upd_success_batch = "CALL UTILITY.EDW_BATCH_SUCCESS_PROC('"~v_dbt_job_name~"')" -%}

{################# Snowflake Object Configuration #################}
{{
    config(
         description = 'Building ETL table PORTFOLIOANALYSES_WEEKLY_SNAPSHOT for NPD LANDING PROJECT'
        ,transient=true   
        ,materialized='table'
        ,schema ='ETL_ODS_NPD'
        ,alias= 'MSPROJECTS_PORTFOLIOANALYSES_WEEKLY_SNAPSHOT'
        ,tags =['ODS_NPD']
        ,post_hook= [v_sql_upd_success_batch]	
        )
}}

WITH FISCAL_WEEK AS 
(
    SELECT 
        DISTINCT FISCAL_WEEK_KEY
    FROM 
    {{ref('MART_DATE') }}
    WHERE 
        CALENDAR_DATE = (CURRENT_TIMESTAMP() - INTERVAL '7 HOUR')::DATE
        or CALENDAR_DATE = (CURRENT_TIMESTAMP() )::DATE
)

,PORTFOLIOANALYSES AS (
SELECT ANALYSISID
, ALTERNATEPROJECTENDDATECUSTOMFIELDID
, ALTERNATEPROJECTENDDATECUSTOMFIELDNAME
, ALTERNATEPROJECTSTARTDATECUSTOMFIELDID
, ALTERNATEPROJECTSTARTDATECUSTOMFIELDNAME
, ANALYSISDESCRIPTION
, ANALYSISNAME
, ANALYSISTYPE
, BOOKINGTYPE
, CREATEDBYRESOURCEID
, CREATEDBYRESOURCENAME
, CREATEDDATE
, DEPARTMENTID
, DEPARTMENTNAME
, FILTERRESOURCESBYDEPARTMENT
, FILTERRESOURCESBYRBS
, FILTERRESOURCESBYRBSVALUEID
, FILTERRESOURCESBYRBSVALUETEXT
, FORCEDINALIASLOOKUPTABLEID
, FORCEDINALIASLOOKUPTABLENAME
, FORCEDOUTALIASLOOKUPTABLEID
, FORCEDOUTALIASLOOKUPTABLENAME
, HARDCONSTRAINTCUSTOMFIELDID
, HARDCONSTRAINTCUSTOMFIELDNAME
, MODIFIEDBYRESOURCEID
, MODIFIEDBYRESOURCENAME
, MODIFIEDDATE
, PLANNINGHORIZONENDDATE
, PLANNINGHORIZONSTARTDATE
, PRIORITIZATIONID
, PRIORITIZATIONNAME
, PRIORITIZATIONTYPE
, ROLECUSTOMFIELDID
, ROLECUSTOMFIELDNAME
, TIMESCALE
, USEALTERNATEPROJECTDATESFORRESOURCEPLANS
, LINKEDANALYSISPROJECTS
, LINKEDCOSTCONSTRAINTSCENARIOS
, LINKEDCREATEDBYRESOURCE
, LINKEDMODIFIEDBYRESOURCE
, LINKEDPRIORITIZATION
, LINKEDRESOURCECONSTRAINTSCENARIOS
, BIW_INS_DTTM
, BIW_UPD_DTTM
FROM 
    {{source ('STG_NPD_MSPROJECTS_ODATAV1','PORTFOLIOANALYSES')}}  
    QUALIFY( ROW_NUMBER() OVER (PARTITION BY ANALYSISID  ORDER BY BIW_UPD_DTTM DESC) =1)
)

SELECT 
    MD5(OBJECT_CONSTRUCT (  'COL1',FSC_WK.FISCAL_WEEK_KEY::STRING
                            ,'COL2',STG.ANALYSISID::STRING
                         )::STRING 
        )::BINARY AS PORTFOLIOANALYSES_KEY 
    ,FSC_WK.FISCAL_WEEK_KEY AS SNAPSHOT_WEEK_KEY
    ,ANALYSISID
, STG.ALTERNATEPROJECTENDDATECUSTOMFIELDID
, STG.ALTERNATEPROJECTENDDATECUSTOMFIELDNAME
, STG.ALTERNATEPROJECTSTARTDATECUSTOMFIELDID
, STG.ALTERNATEPROJECTSTARTDATECUSTOMFIELDNAME
, STG.ANALYSISDESCRIPTION
, STG.ANALYSISNAME
, STG.ANALYSISTYPE
, STG.BOOKINGTYPE
, STG.CREATEDBYRESOURCEID
, STG.CREATEDBYRESOURCENAME
, STG.CREATEDDATE
, STG.DEPARTMENTID
, STG.DEPARTMENTNAME
, STG.FILTERRESOURCESBYDEPARTMENT
, STG.FILTERRESOURCESBYRBS
, STG.FILTERRESOURCESBYRBSVALUEID
, STG.FILTERRESOURCESBYRBSVALUETEXT
, STG.FORCEDINALIASLOOKUPTABLEID
, STG.FORCEDINALIASLOOKUPTABLENAME
, STG.FORCEDOUTALIASLOOKUPTABLEID
, STG.FORCEDOUTALIASLOOKUPTABLENAME
, STG.HARDCONSTRAINTCUSTOMFIELDID
, STG.HARDCONSTRAINTCUSTOMFIELDNAME
, STG.MODIFIEDBYRESOURCEID
, STG.MODIFIEDBYRESOURCENAME
, STG.MODIFIEDDATE
, STG.PLANNINGHORIZONENDDATE
, STG.PLANNINGHORIZONSTARTDATE
, STG.PRIORITIZATIONID
, STG.PRIORITIZATIONNAME
, STG.PRIORITIZATIONTYPE
, STG.ROLECUSTOMFIELDID
, STG.ROLECUSTOMFIELDNAME
, STG.TIMESCALE
, STG.USEALTERNATEPROJECTDATESFORRESOURCEPLANS
, STG.LINKEDANALYSISPROJECTS
, STG.LINKEDCOSTCONSTRAINTSCENARIOS
, STG.LINKEDCREATEDBYRESOURCE
, STG.LINKEDMODIFIEDBYRESOURCE
, STG.LINKEDPRIORITIZATION
,STG.LINKEDRESOURCECONSTRAINTSCENARIOS
,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_INS_DTTM 
    ,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_UPD_DTTM 
   ,{{V_BIW_BATCH_ID}}::NUMBER as BIW_BATCH_ID 
   ,md5(object_construct ('COL1',ANALYSISID::string ,'COL2',ALTERNATEPROJECTENDDATECUSTOMFIELDID::string ,'COL3',ALTERNATEPROJECTENDDATECUSTOMFIELDNAME::string ,'COL4',ALTERNATEPROJECTSTARTDATECUSTOMFIELDID::string ,'COL5',ALTERNATEPROJECTSTARTDATECUSTOMFIELDNAME::string ,'COL6',ANALYSISDESCRIPTION::string ,'COL7',ANALYSISNAME::string ,'COL8',ANALYSISTYPE::string ,'COL9',BOOKINGTYPE::string ,'COL10',CREATEDBYRESOURCEID::string ,'COL11',CREATEDBYRESOURCENAME::string ,'COL12',CREATEDDATE::string ,'COL13',DEPARTMENTID::string ,'COL14',DEPARTMENTNAME::string ,'COL15',FILTERRESOURCESBYDEPARTMENT::string ,'COL16',FILTERRESOURCESBYRBS::string ,'COL17',FILTERRESOURCESBYRBSVALUEID::string ,'COL18',FILTERRESOURCESBYRBSVALUETEXT::string ,'COL19',FORCEDINALIASLOOKUPTABLEID::string ,'COL20',FORCEDINALIASLOOKUPTABLENAME::string ,'COL21',FORCEDOUTALIASLOOKUPTABLEID::string ,'COL22',FORCEDOUTALIASLOOKUPTABLENAME::string ,'COL23',HARDCONSTRAINTCUSTOMFIELDID::string ,'COL24',HARDCONSTRAINTCUSTOMFIELDNAME::string ,'COL25',MODIFIEDBYRESOURCEID::string ,'COL26',MODIFIEDBYRESOURCENAME::string ,'COL27',MODIFIEDDATE::string ,'COL28',PLANNINGHORIZONENDDATE::string ,'COL29',PLANNINGHORIZONSTARTDATE::string ,'COL30',PRIORITIZATIONID::string ,'COL31',PRIORITIZATIONNAME::string ,'COL32',PRIORITIZATIONTYPE::string ,'COL33',ROLECUSTOMFIELDID::string ,'COL34',ROLECUSTOMFIELDNAME::string ,'COL35',TIMESCALE::string ,'COL36',USEALTERNATEPROJECTDATESFORRESOURCEPLANS::string ,'COL37',LINKEDANALYSISPROJECTS::string ,'COL38',LINKEDCOSTCONSTRAINTSCENARIOS::string ,'COL39',LINKEDCREATEDBYRESOURCE::string ,'COL40',LINKEDMODIFIEDBYRESOURCE::string ,'COL41',LINKEDPRIORITIZATION::string ,'COL42',LINKEDRESOURCECONSTRAINTSCENARIOS::string)::string )::BINARY as BIW_MD5_KEY

FROM     
PORTFOLIOANALYSES  STG 

CROSS JOIN FISCAL_WEEK FSC_WK
