
/*---------------------------------------------------------------------------
Command to run model:
-- dbt run --select ETL_ODS_NPD_MSPROJECTS_RESOURCES_WEEKLY_SNAPSHOT 
-- dbt build --full-refresh --select ETL_ODS_NPD_MSPROJECTS_RESOURCES_WEEKLY_SNAPSHOT 

Version     Date            Author              Description
-------     --------        -----------         ----------------------------------
1.0         25-JAN-2023     KALI DANDAPANI      Initial Version
---------------------------------------------------------------------------*/

{################# EDW Job Template Variables #################}
{%-set v_pk_list = ['RESOURCEID']-%}

{################# Batch control insert and update SQL #################}
{%- set v_dbt_job_name = 'DBT_ETL_ODS_NPD_MSPROJECTS_RESOURCES_WEEKLY_SNAPSHOT'-%}
-- Step 1 Batch process info
{%- set v_watermark = edw_batch_control(v_dbt_job_name,config.get('schema'),config.get('alias') ,config.get('tags'),config.get('materialized') ) -%}
{%- set V_LWM = v_watermark[0] -%}
{%- set V_HWM = v_watermark[1] -%}
{%- set V_START_DTTM = v_watermark[2] -%}
{%- set V_BIW_BATCH_ID = v_watermark[3] -%}
{%- set v_sql_upd_success_batch = "CALL UTILITY.EDW_BATCH_SUCCESS_PROC('"~v_dbt_job_name~"')" -%}

{################# Snowflake Object Configuration #################}
{{
    config(
         description = 'Building ETL table RESOURCES_WEEKLY_SNAPSHOT for NPD LANDING PROJECT'
        ,transient=true   
        ,materialized='table'
        ,schema ='ETL_ODS_NPD'
        ,alias= 'MSPROJECTS_RESOURCES_WEEKLY_SNAPSHOT'
        ,tags =['ODS_NPD']
        ,post_hook= [v_sql_upd_success_batch]	
        )
}}

WITH FISCAL_WEEK AS 
(
    SELECT 
        DISTINCT FISCAL_WEEK_KEY
    FROM 
    {{ref('MART_DATE') }}
    WHERE 
        CALENDAR_DATE = (CURRENT_TIMESTAMP() - INTERVAL '7 HOUR')::DATE
        or CALENDAR_DATE = (CURRENT_TIMESTAMP() )::DATE
)

,RESOURCES AS (
SELECT RESOURCEID
, COSTTYPE
, RBS
, RESOURCEBASECALENDAR
, RESOURCEBOOKINGTYPE
, RESOURCECANLEVEL
, RESOURCECODE
, RESOURCECOSTCENTER
, RESOURCECOSTPERUSE
, RESOURCECREATEDDATE
, RESOURCEDEPARTMENTS
, RESOURCEEARLIESTAVAILABLEFROM
, RESOURCEEMAILADDRESS
, RESOURCEGROUP
, RESOURCEHYPERLINK
, RESOURCEHYPERLINKHREF
, RESOURCEINITIALS
, RESOURCEISACTIVE
, RESOURCEISGENERIC
, RESOURCEISTEAM
, RESOURCELATESTAVAILABLETO
, RESOURCEMATERIALLABEL
, RESOURCEMAXUNITS
, RESOURCEMODIFIEDDATE
, RESOURCENAME
, RESOURCENTACCOUNT
, RESOURCEOVERTIMERATE
, RESOURCESTANDARDRATE
, RESOURCESTATUSID
, RESOURCESTATUSNAME
, RESOURCETIMESHEETMANAGEID
, RESOURCETYPE
, RESOURCEWORKGROUP
, ROLE
, TYPEDESCRIPTION
, TYPENAME
, LINKEDASSIGNMENTS
, LINKEDRESOURCEDEMANDTIMEPHASEDINFO
, LINKEDTIMEPHASEDINFODATASET
, BIW_INS_DTTM
, BIW_UPD_DTTM
FROM 
    {{source ('STG_NPD_MSPROJECTS_ODATAV1','RESOURCES')}}  
    QUALIFY( ROW_NUMBER() OVER (PARTITION BY RESOURCEID  ORDER BY BIW_UPD_DTTM DESC) =1)
)

SELECT 
    MD5(OBJECT_CONSTRUCT (  'COL1',FSC_WK.FISCAL_WEEK_KEY::STRING
                            ,'COL2',STG.RESOURCEID::STRING
                         )::STRING 
        )::BINARY AS RESOURCES_KEY 
    ,FSC_WK.FISCAL_WEEK_KEY AS SNAPSHOT_WEEK_KEY
    ,RESOURCEID
, STG.COSTTYPE
, STG.RBS
, STG.RESOURCEBASECALENDAR
, STG.RESOURCEBOOKINGTYPE
, STG.RESOURCECANLEVEL
, STG.RESOURCECODE
, STG.RESOURCECOSTCENTER
, STG.RESOURCECOSTPERUSE
, STG.RESOURCECREATEDDATE
, STG.RESOURCEDEPARTMENTS
, STG.RESOURCEEARLIESTAVAILABLEFROM
, STG.RESOURCEEMAILADDRESS
, STG.RESOURCEGROUP
, STG.RESOURCEHYPERLINK
, STG.RESOURCEHYPERLINKHREF
, STG.RESOURCEINITIALS
, STG.RESOURCEISACTIVE
, STG.RESOURCEISGENERIC
, STG.RESOURCEISTEAM
, STG.RESOURCELATESTAVAILABLETO
, STG.RESOURCEMATERIALLABEL
, STG.RESOURCEMAXUNITS
, STG.RESOURCEMODIFIEDDATE
, STG.RESOURCENAME
, STG.RESOURCENTACCOUNT
, STG.RESOURCEOVERTIMERATE
, STG.RESOURCESTANDARDRATE
, STG.RESOURCESTATUSID
, STG.RESOURCESTATUSNAME
, STG.RESOURCETIMESHEETMANAGEID
, STG.RESOURCETYPE
, STG.RESOURCEWORKGROUP
, STG.ROLE
, STG.TYPEDESCRIPTION
, STG.TYPENAME
, STG.LINKEDASSIGNMENTS
, STG.LINKEDRESOURCEDEMANDTIMEPHASEDINFO
,STG.LINKEDTIMEPHASEDINFODATASET
,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_INS_DTTM 
    ,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_UPD_DTTM 
   ,{{V_BIW_BATCH_ID}}::NUMBER as BIW_BATCH_ID 
   ,md5(object_construct ('COL1',RESOURCEID::string ,'COL2',COSTTYPE::string ,'COL3',RBS::string ,'COL4',RESOURCEBASECALENDAR::string ,'COL5',RESOURCEBOOKINGTYPE::string ,'COL6',RESOURCECANLEVEL::string ,'COL7',RESOURCECODE::string ,'COL8',RESOURCECOSTCENTER::string ,'COL9',RESOURCECOSTPERUSE::string ,'COL10',RESOURCECREATEDDATE::string ,'COL11',RESOURCEDEPARTMENTS::string ,'COL12',RESOURCEEARLIESTAVAILABLEFROM::string ,'COL13',RESOURCEEMAILADDRESS::string ,'COL14',RESOURCEGROUP::string ,'COL15',RESOURCEHYPERLINK::string ,'COL16',RESOURCEHYPERLINKHREF::string ,'COL17',RESOURCEINITIALS::string ,'COL18',RESOURCEISACTIVE::string ,'COL19',RESOURCEISGENERIC::string ,'COL20',RESOURCEISTEAM::string ,'COL21',RESOURCELATESTAVAILABLETO::string ,'COL22',RESOURCEMATERIALLABEL::string ,'COL23',RESOURCEMAXUNITS::string ,'COL24',RESOURCEMODIFIEDDATE::string ,'COL25',RESOURCENAME::string ,'COL26',RESOURCENTACCOUNT::string ,'COL27',RESOURCEOVERTIMERATE::string ,'COL28',RESOURCESTANDARDRATE::string ,'COL29',RESOURCESTATUSID::string ,'COL30',RESOURCESTATUSNAME::string ,'COL31',RESOURCETIMESHEETMANAGEID::string ,'COL32',RESOURCETYPE::string ,'COL33',RESOURCEWORKGROUP::string ,'COL34',ROLE::string ,'COL35',TYPEDESCRIPTION::string ,'COL36',TYPENAME::string ,'COL37',LINKEDASSIGNMENTS::string ,'COL38',LINKEDRESOURCEDEMANDTIMEPHASEDINFO::string ,'COL39',LINKEDTIMEPHASEDINFODATASET::string )::string )::BINARY as BIW_MD5_KEY

FROM     
RESOURCES  STG 

CROSS JOIN FISCAL_WEEK FSC_WK
