
/*---------------------------------------------------------------------------
Command to run model:
-- dbt run --select ETL_ODS_NPD_MSPROJECTS_TIMESHEETLINES_WEEKLY_SNAPSHOT 
-- dbt build --full-refresh --select ETL_ODS_NPD_MSPROJECTS_TIMESHEETLINES_WEEKLY_SNAPSHOT 

Version     Date            Author              Description
-------     --------        -----------         ----------------------------------
1.0         25-JAN-2023     KALI DANDAPANI      Initial Version
---------------------------------------------------------------------------*/

{################# EDW Job Template Variables #################}
{%-set v_pk_list = ['TIMESHEETLINEID']-%}

{################# Batch control insert and update SQL #################}
{%- set v_dbt_job_name = 'DBT_ETL_ODS_NPD_MSPROJECTS_TIMESHEETLINES_WEEKLY_SNAPSHOT'-%}
-- Step 1 Batch process info
{%- set v_watermark = edw_batch_control(v_dbt_job_name,config.get('schema'),config.get('alias') ,config.get('tags'),config.get('materialized') ) -%}
{%- set V_LWM = v_watermark[0] -%}
{%- set V_HWM = v_watermark[1] -%}
{%- set V_START_DTTM = v_watermark[2] -%}
{%- set V_BIW_BATCH_ID = v_watermark[3] -%}
{%- set v_sql_upd_success_batch = "CALL UTILITY.EDW_BATCH_SUCCESS_PROC('"~v_dbt_job_name~"')" -%}

{################# Snowflake Object Configuration #################}
{{
    config(
         description = 'Building ETL table TIMESHEETLINES_WEEKLY_SNAPSHOT for NPD LANDING PROJECT'
        ,transient=true   
        ,materialized='table'
        ,schema ='ETL_ODS_NPD'
        ,alias= 'MSPROJECTS_TIMESHEETLINES_WEEKLY_SNAPSHOT'
        ,tags =['ODS_NPD']
        ,post_hook= [v_sql_upd_success_batch]	
        )
}}

WITH FISCAL_WEEK AS 
(
    SELECT 
        DISTINCT FISCAL_WEEK_KEY
    FROM 
    {{ref('MART_DATE') }}
    WHERE 
        CALENDAR_DATE = (CURRENT_TIMESTAMP() - INTERVAL '7 HOUR')::DATE
        or CALENDAR_DATE = (CURRENT_TIMESTAMP() )::DATE
)

,TIMESHEETLINES AS (
SELECT TIMESHEETLINEID
, ACTUALOVERTIMEWORKBILLABLE
, ACTUALOVERTIMEWORKNONBILLABLE
, ACTUALWORKBILLABLE
, ACTUALWORKNONBILLABLE
, ASSIGNMENTID
, CREATEDDATE
, LASTSAVEDWORK
, LCID
, MODIFIEDDATE
, PERIODENDDATE
, PERIODSTARTDATE
, PLANNEDWORK
, PROJECTID
, PROJECTNAME
, TASKHIERARCHY
, TASKID
, TASKNAME
, TIMESHEETAPPROVERRESOURCEID
, TIMESHEETAPPROVERRESOURCENAME
, TIMESHEETCLASSDESCRIPTION
, TIMESHEETCLASSID
, TIMESHEETCLASSNAME
, TIMESHEETCLASSTYPE
, TIMESHEETID
, TIMESHEETLINECOMMENT
, TIMESHEETLINESTATUS
, TIMESHEETLINESTATUSID
, TIMESHEETNAME
, TIMESHEETOWNER
, TIMESHEETOWNERID
, TIMESHEETPERIODID
, TIMESHEETPERIODNAME
, TIMESHEETPERIODSTATUS
, TIMESHEETPERIODSTATUSID
, TIMESHEETSTATUS
, TIMESHEETSTATUSID
, LINKEDACTUALS
, LINKEDAPPROVERRESOURCE
, LINKEDTIMESHEET
, LINKEDTIMESHEETCLASS
, BIW_INS_DTTM
, BIW_UPD_DTTM
FROM 
    {{source ('STG_NPD_MSPROJECTS_ODATAV1','TIMESHEETLINES')}}  
    QUALIFY( ROW_NUMBER() OVER (PARTITION BY TIMESHEETLINEID  ORDER BY BIW_UPD_DTTM DESC) =1)
)

SELECT 
    MD5(OBJECT_CONSTRUCT (  'COL1',FSC_WK.FISCAL_WEEK_KEY::STRING
                            ,'COL2',STG.TIMESHEETLINEID::STRING
                         )::STRING 
        )::BINARY AS TIMESHEETLINES_KEY 
    ,FSC_WK.FISCAL_WEEK_KEY AS SNAPSHOT_WEEK_KEY
    ,TIMESHEETLINEID
, STG.ACTUALOVERTIMEWORKBILLABLE
, STG.ACTUALOVERTIMEWORKNONBILLABLE
, STG.ACTUALWORKBILLABLE
, STG.ACTUALWORKNONBILLABLE
, STG.ASSIGNMENTID
, STG.CREATEDDATE
, STG.LASTSAVEDWORK
, STG.LCID
, STG.MODIFIEDDATE
, STG.PERIODENDDATE
, STG.PERIODSTARTDATE
, STG.PLANNEDWORK
, STG.PROJECTID
, STG.PROJECTNAME
, STG.TASKHIERARCHY
, STG.TASKID
, STG.TASKNAME
, STG.TIMESHEETAPPROVERRESOURCEID
, STG.TIMESHEETAPPROVERRESOURCENAME
, STG.TIMESHEETCLASSDESCRIPTION
, STG.TIMESHEETCLASSID
, STG.TIMESHEETCLASSNAME
, STG.TIMESHEETCLASSTYPE
, STG.TIMESHEETID
, STG.TIMESHEETLINECOMMENT
, STG.TIMESHEETLINESTATUS
, STG.TIMESHEETLINESTATUSID
, STG.TIMESHEETNAME
, STG.TIMESHEETOWNER
, STG.TIMESHEETOWNERID
, STG.TIMESHEETPERIODID
, STG.TIMESHEETPERIODNAME
, STG.TIMESHEETPERIODSTATUS
, STG.TIMESHEETPERIODSTATUSID
, STG.TIMESHEETSTATUS
, STG.TIMESHEETSTATUSID
, STG.LINKEDACTUALS
, STG.LINKEDAPPROVERRESOURCE
, STG.LINKEDTIMESHEET
,STG.LINKEDTIMESHEETCLASS
,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_INS_DTTM 
    ,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_UPD_DTTM 
   ,{{V_BIW_BATCH_ID}}::NUMBER as BIW_BATCH_ID
   ,md5(object_construct ('COL1',TIMESHEETLINEID::string ,'COL2',ACTUALOVERTIMEWORKBILLABLE::string ,'COL3',ACTUALOVERTIMEWORKNONBILLABLE::string ,'COL4',ACTUALWORKBILLABLE::string ,'COL5',ACTUALWORKNONBILLABLE::string ,'COL6',ASSIGNMENTID::string ,'COL7',CREATEDDATE::string ,'COL8',LASTSAVEDWORK::string ,'COL9',LCID::string ,'COL10',MODIFIEDDATE::string ,'COL11',PERIODENDDATE::string ,'COL12',PERIODSTARTDATE::string ,'COL13',PLANNEDWORK::string ,'COL14',PROJECTID::string ,'COL15',PROJECTNAME::string ,'COL16',TASKHIERARCHY::string ,'COL17',TASKID::string ,'COL18',TASKNAME::string ,'COL19',TIMESHEETAPPROVERRESOURCEID::string ,'COL20',TIMESHEETAPPROVERRESOURCENAME::string ,'COL21',TIMESHEETCLASSDESCRIPTION::string ,'COL22',TIMESHEETCLASSID::string ,'COL23',TIMESHEETCLASSNAME::string ,'COL24',TIMESHEETCLASSTYPE::string ,'COL25',TIMESHEETID::string ,'COL26',TIMESHEETLINECOMMENT::string ,'COL27',TIMESHEETLINESTATUS::string ,'COL28',TIMESHEETLINESTATUSID::string ,'COL29',TIMESHEETNAME::string ,'COL30',TIMESHEETOWNER::string ,'COL31',TIMESHEETOWNERID::string ,'COL32',TIMESHEETPERIODID::string ,'COL33',TIMESHEETPERIODNAME::string ,'COL34',TIMESHEETPERIODSTATUS::string ,'COL35',TIMESHEETPERIODSTATUSID::string ,'COL36',TIMESHEETSTATUS::string ,'COL37',TIMESHEETSTATUSID::string ,'COL38',LINKEDACTUALS::string ,'COL39',LINKEDAPPROVERRESOURCE::string ,'COL40',LINKEDTIMESHEET::string ,'COL41',LINKEDTIMESHEETCLASS::string )::string )::BINARY as BIW_MD5_KEY

FROM     
TIMESHEETLINES  STG 

CROSS JOIN FISCAL_WEEK FSC_WK
