
/*---------------------------------------------------------------------------
Command to run model:
-- dbt run --select ETL_ODS_NPD_MSPROJECTS_RESOURCECONSTRAINTSCENARIOS_WEEKLY_SNAPSHOT 
-- dbt build --full-refresh --select ETL_ODS_NPD_MSPROJECTS_RESOURCECONSTRAINTSCENARIOS_WEEKLY_SNAPSHOT 

Version     Date            Author              Description
-------     --------        -----------         ----------------------------------
1.0         25-JAN-2023     KALI DANDAPANI      Initial Version
---------------------------------------------------------------------------*/

{################# EDW Job Template Variables #################}
{%-set v_pk_list = ['SCENARIOID']-%}

{################# Batch control insert and update SQL #################}
{%- set v_dbt_job_name = 'DBT_ETL_ODS_NPD_MSPROJECTS_RESOURCECONSTRAINTSCENARIOS_WEEKLY_SNAPSHOT'-%}
-- Step 1 Batch process info
{%- set v_watermark = edw_batch_control(v_dbt_job_name,config.get('schema'),config.get('alias') ,config.get('tags'),config.get('materialized') ) -%}
{%- set V_LWM = v_watermark[0] -%}
{%- set V_HWM = v_watermark[1] -%}
{%- set V_START_DTTM = v_watermark[2] -%}
{%- set V_BIW_BATCH_ID = v_watermark[3] -%}
{%- set v_sql_upd_success_batch = "CALL UTILITY.EDW_BATCH_SUCCESS_PROC('"~v_dbt_job_name~"')" -%}

{################# Snowflake Object Configuration #################}
{{
    config(
         description = 'Building ETL table RESOURCECONSTRAINTSCENARIOS_WEEKLY_SNAPSHOT for NPD LANDING PROJECT'
        ,transient=true   
        ,materialized='table'
        ,schema ='ETL_ODS_NPD'
        ,alias= 'MSPROJECTS_RESOURCECONSTRAINTSCENARIOS_WEEKLY_SNAPSHOT'
        ,tags =['ODS_NPD']
        ,post_hook= [v_sql_upd_success_batch]	
        )
}}

WITH FISCAL_WEEK AS 
(
    SELECT 
        DISTINCT FISCAL_WEEK_KEY
    FROM 
    {{ref('MART_DATE') }}
    WHERE 
        CALENDAR_DATE = (CURRENT_TIMESTAMP() - INTERVAL '7 HOUR')::DATE
        or CALENDAR_DATE = (CURRENT_TIMESTAMP() )::DATE
)

,RESOURCECONSTRAINTSCENARIOS AS (
SELECT SCENARIOID
, ALLOCATIONTHRESHOLD
, ANALYSISID
, ANALYSISNAME
, CONSTRAINTTYPE
, CONSTRAINTVALUE
, COSTCONSTRAINTSCENARIOID
, COSTCONSTRAINTSCENARIONAME
, CREATEDBYRESOURCEID
, CREATEDBYRESOURCENAME
, CREATEDDATE
, ENFORCEPROJECTDEPENDENCIES
, ENFORCESCHEDULINGCONSTRAINTS
, HIRINGTYPE
, MODIFIEDBYRESOURCEID
, MODIFIEDBYRESOURCENAME
, MODIFIEDDATE
, RATETABLE
, SCENARIODESCRIPTION
, SCENARIONAME
, LINKEDANALYSIS
, LINKEDCOSTCONSTRAINTSCENARIO
, LINKEDCREATEDBYRESOURCE
, LINKEDMODIFIEDBYRESOURCE
, LINKEDRESOURCESCENARIOPROJECTS
, BIW_INS_DTTM
, BIW_UPD_DTTM
FROM 
    {{source ('STG_NPD_MSPROJECTS_ODATAV1','RESOURCECONSTRAINTSCENARIOS')}}  
    QUALIFY( ROW_NUMBER() OVER (PARTITION BY SCENARIOID  ORDER BY BIW_UPD_DTTM DESC) =1)
)

SELECT 
    MD5(OBJECT_CONSTRUCT (  'COL1',FSC_WK.FISCAL_WEEK_KEY::STRING
                            ,'COL2',STG.SCENARIOID::STRING
                         )::STRING 
        )::BINARY AS RESOURCECONSTRAINTSCENARIOS_KEY 
    ,FSC_WK.FISCAL_WEEK_KEY AS SNAPSHOT_WEEK_KEY
    ,SCENARIOID
, STG.ALLOCATIONTHRESHOLD
, STG.ANALYSISID
, STG.ANALYSISNAME
, STG.CONSTRAINTTYPE
, STG.CONSTRAINTVALUE
, STG.COSTCONSTRAINTSCENARIOID
, STG.COSTCONSTRAINTSCENARIONAME
, STG.CREATEDBYRESOURCEID
, STG.CREATEDBYRESOURCENAME
, STG.CREATEDDATE
, STG.ENFORCEPROJECTDEPENDENCIES
, STG.ENFORCESCHEDULINGCONSTRAINTS
, STG.HIRINGTYPE
, STG.MODIFIEDBYRESOURCEID
, STG.MODIFIEDBYRESOURCENAME
, STG.MODIFIEDDATE
, STG.RATETABLE
, STG.SCENARIODESCRIPTION
, STG.SCENARIONAME
, STG.LINKEDANALYSIS
, STG.LINKEDCOSTCONSTRAINTSCENARIO
, STG.LINKEDCREATEDBYRESOURCE
, STG.LINKEDMODIFIEDBYRESOURCE
,STG.LINKEDRESOURCESCENARIOPROJECTS
,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_INS_DTTM 
    ,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_UPD_DTTM 
   ,{{V_BIW_BATCH_ID}}::NUMBER as BIW_BATCH_ID 
   ,md5(object_construct ('COL1',SCENARIOID::string ,'COL2',ALLOCATIONTHRESHOLD::string ,'COL3',ANALYSISID::string ,'COL4',ANALYSISNAME::string ,'COL5',CONSTRAINTTYPE::string ,'COL6',CONSTRAINTVALUE::string ,'COL7',COSTCONSTRAINTSCENARIOID::string ,'COL8',COSTCONSTRAINTSCENARIONAME::string ,'COL9',CREATEDBYRESOURCEID::string ,'COL10',CREATEDBYRESOURCENAME::string ,'COL11',CREATEDDATE::string ,'COL12',ENFORCEPROJECTDEPENDENCIES::string ,'COL13',ENFORCESCHEDULINGCONSTRAINTS::string ,'COL14',HIRINGTYPE::string ,'COL15',MODIFIEDBYRESOURCEID::string ,'COL16',MODIFIEDBYRESOURCENAME::string ,'COL17',MODIFIEDDATE::string ,'COL18',RATETABLE::string ,'COL19',SCENARIODESCRIPTION::string ,'COL20',SCENARIONAME::string ,'COL21',LINKEDANALYSIS::string ,'COL22',LINKEDCOSTCONSTRAINTSCENARIO::string ,'COL23',LINKEDCREATEDBYRESOURCE::string ,'COL24',LINKEDMODIFIEDBYRESOURCE::string ,'COL25',LINKEDRESOURCESCENARIOPROJECTS::string )::string )::BINARY as BIW_MD5_KEY

FROM     
RESOURCECONSTRAINTSCENARIOS  STG 

CROSS JOIN FISCAL_WEEK FSC_WK
