/*---------------------------------------------------------------------------
Command to run model:
-- dbt run --select ETL_ODS_NPD_MSPROJECTS_ASSIGNMENTTIMEPHASEDDATASET_WEEKLY_SNAPSHOT 
-- dbt build --full-refresh --select ETL_ODS_NPD_MSPROJECTS_ASSIGNMENTTIMEPHASEDDATASET_WEEKLY_SNAPSHOT 
pk: AssignmentId  ,ProjectId,TimeByDay 
Version     Date            Author              Description
-------     --------        -----------         ----------------------------------
1.0         25-JAN-2023     KALI DANDAPANI      Initial Version
---------------------------------------------------------------------------*/

{################# EDW Job Template Variables #################}
{%-set v_pk_list = ['AssignmentId' ,'ProjectId','TimeByDay']-%}

{################# Batch control insert and update SQL #################}
{%- set v_dbt_job_name = 'DBT_ETL_ODS_NPD_MSPROJECTS_ASSIGNMENTTIMEPHASEDDATASET_WEEKLY_SNAPSHOT'-%}
-- Step 1 Batch process info
{%- set v_watermark = edw_batch_control(v_dbt_job_name,config.get('schema'),config.get('alias') ,config.get('tags'),config.get('materialized') ) -%}
{%- set V_LWM = v_watermark[0] -%}
{%- set V_HWM = v_watermark[1] -%}
{%- set V_START_DTTM = v_watermark[2] -%}
{%- set V_BIW_BATCH_ID = v_watermark[3] -%}
{%- set v_sql_upd_success_batch = "CALL UTILITY.EDW_BATCH_SUCCESS_PROC('"~v_dbt_job_name~"')" -%}

{################# Snowflake Object Configuration #################}
{{
    config(
         description = 'Building ETL table ASSIGNMENTTIMEPHASEDDATASET_WEEKLY_SNAPSHOT for NPD LANDING PROJECT'
        ,transient=true   
        ,materialized='table'
        ,schema ='ETL_ODS_NPD'
        ,alias= 'MSPROJECTS_ASSIGNMENTTIMEPHASEDDATASET_WEEKLY_SNAPSHOT'
        ,tags =['ODS_NPD']
        ,post_hook= [v_sql_upd_success_batch]	
        )
}}

WITH FISCAL_WEEK AS 
(
    SELECT 
        DISTINCT FISCAL_WEEK_KEY
    FROM 
    {{ref('MART_DATE') }}
    WHERE 
        CALENDAR_DATE = (CURRENT_TIMESTAMP() - INTERVAL '7 HOUR')::DATE
        or CALENDAR_DATE = (CURRENT_TIMESTAMP() )::DATE
)

,ASSIGNMENTTIMEPHASEDDATASET AS (
SELECT ASSIGNMENTID
, PROJECTID
, TIMEBYDAY
, ASSIGNMENTACTUALCOST
, ASSIGNMENTACTUALOVERTIMECOST
, ASSIGNMENTACTUALOVERTIMEWORK
, ASSIGNMENTACTUALREGULARCOST
, ASSIGNMENTACTUALREGULARWORK
, ASSIGNMENTACTUALWORK
, ASSIGNMENTBUDGETCOST
, ASSIGNMENTBUDGETMATERIALWORK
, ASSIGNMENTBUDGETWORK
, ASSIGNMENTCOMBINEDWORK
, ASSIGNMENTCOST
, ASSIGNMENTMATERIALACTUALWORK
, ASSIGNMENTMATERIALWORK
, ASSIGNMENTMODIFIEDDATE
, ASSIGNMENTOVERTIMECOST
, ASSIGNMENTOVERTIMEWORK
, ASSIGNMENTREGULARCOST
, ASSIGNMENTREGULARWORK
, ASSIGNMENTREMAININGCOST
, ASSIGNMENTREMAININGOVERTIMECOST
, ASSIGNMENTREMAININGOVERTIMEWORK
, ASSIGNMENTREMAININGREGULARCOST
, ASSIGNMENTREMAININGREGULARWORK
, ASSIGNMENTREMAININGWORK
, ASSIGNMENTRESOURCEPLANWORK
, ASSIGNMENTWORK
, FISCALPERIODID
, PROJECTNAME
, RESOURCEID
, TASKID
, TASKISACTIVE
, TASKNAME
, LINKEDASSIGNMENT
, LINKEDPROJECT
, LINKEDTASK
, LINKEDTIME
, BIW_INS_DTTM
, BIW_UPD_DTTM
FROM 
    {{source ('STG_NPD_MSPROJECTS_ODATAV1','ASSIGNMENTTIMEPHASEDDATASET')}}  
    QUALIFY( ROW_NUMBER() OVER (PARTITION BY AssignmentId  ,ProjectId,TimeByDay  ORDER BY BIW_UPD_DTTM DESC) =1)
)

SELECT 
    MD5(OBJECT_CONSTRUCT (  'COL1',FSC_WK.FISCAL_WEEK_KEY::STRING
                            ,'COL2',STG.ASSIGNMENTID::STRING
                            ,'COL3',STG.ProjectId::STRING 
                            ,'COL4',STG.TimeByDay::STRING 
                         )::STRING 
        )::BINARY AS ASSIGNMENTTIMEPHASEDDATASET_KEY 
    ,FSC_WK.FISCAL_WEEK_KEY AS SNAPSHOT_WEEK_KEY
    ,ASSIGNMENTID
, STG.PROJECTID
, STG.TIMEBYDAY
, STG.ASSIGNMENTACTUALCOST
, STG.ASSIGNMENTACTUALOVERTIMECOST
, STG.ASSIGNMENTACTUALOVERTIMEWORK
, STG.ASSIGNMENTACTUALREGULARCOST
, STG.ASSIGNMENTACTUALREGULARWORK
, STG.ASSIGNMENTACTUALWORK
, STG.ASSIGNMENTBUDGETCOST
, STG.ASSIGNMENTBUDGETMATERIALWORK
, STG.ASSIGNMENTBUDGETWORK
, STG.ASSIGNMENTCOMBINEDWORK
, STG.ASSIGNMENTCOST
, STG.ASSIGNMENTMATERIALACTUALWORK
, STG.ASSIGNMENTMATERIALWORK
, STG.ASSIGNMENTMODIFIEDDATE
, STG.ASSIGNMENTOVERTIMECOST
, STG.ASSIGNMENTOVERTIMEWORK
, STG.ASSIGNMENTREGULARCOST
, STG.ASSIGNMENTREGULARWORK
, STG.ASSIGNMENTREMAININGCOST
, STG.ASSIGNMENTREMAININGOVERTIMECOST
, STG.ASSIGNMENTREMAININGOVERTIMEWORK
, STG.ASSIGNMENTREMAININGREGULARCOST
, STG.ASSIGNMENTREMAININGREGULARWORK
, STG.ASSIGNMENTREMAININGWORK
, STG.ASSIGNMENTRESOURCEPLANWORK
, STG.ASSIGNMENTWORK
, STG.FISCALPERIODID
, STG.PROJECTNAME
, STG.RESOURCEID
, STG.TASKID
, STG.TASKISACTIVE
, STG.TASKNAME
, STG.LINKEDASSIGNMENT
, STG.LINKEDPROJECT
, STG.LINKEDTASK
,STG.LINKEDTIME

,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_INS_DTTM 
    ,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_UPD_DTTM 
   ,{{V_BIW_BATCH_ID}}::NUMBER as BIW_BATCH_ID 
   ,md5(object_construct ('COL1',ASSIGNMENTID::string ,'COL2',PROJECTID::string ,'COL3',TIMEBYDAY::string ,'COL4',ASSIGNMENTACTUALCOST::string ,'COL5',ASSIGNMENTACTUALOVERTIMECOST::string ,'COL6',ASSIGNMENTACTUALOVERTIMEWORK::string ,'COL7',ASSIGNMENTACTUALREGULARCOST::string ,'COL8',ASSIGNMENTACTUALREGULARWORK::string ,'COL9',ASSIGNMENTACTUALWORK::string ,'COL10',ASSIGNMENTBUDGETCOST::string ,'COL11',ASSIGNMENTBUDGETMATERIALWORK::string ,'COL12',ASSIGNMENTBUDGETWORK::string ,'COL13',ASSIGNMENTCOMBINEDWORK::string ,'COL14',ASSIGNMENTCOST::string ,'COL15',ASSIGNMENTMATERIALACTUALWORK::string ,'COL16',ASSIGNMENTMATERIALWORK::string ,'COL17',ASSIGNMENTMODIFIEDDATE::string ,'COL18',ASSIGNMENTOVERTIMECOST::string ,'COL19',ASSIGNMENTOVERTIMEWORK::string ,'COL20',ASSIGNMENTREGULARCOST::string ,'COL21',ASSIGNMENTREGULARWORK::string ,'COL22',ASSIGNMENTREMAININGCOST::string ,'COL23',ASSIGNMENTREMAININGOVERTIMECOST::string ,'COL24',ASSIGNMENTREMAININGOVERTIMEWORK::string ,'COL25',ASSIGNMENTREMAININGREGULARCOST::string ,'COL26',ASSIGNMENTREMAININGREGULARWORK::string ,'COL27',ASSIGNMENTREMAININGWORK::string ,'COL28',ASSIGNMENTRESOURCEPLANWORK::string ,'COL29',ASSIGNMENTWORK::string ,'COL30',FISCALPERIODID::string ,'COL31',PROJECTNAME::string ,'COL32',RESOURCEID::string ,'COL33',TASKID::string ,'COL34',TASKISACTIVE::string ,'COL35',TASKNAME::string ,'COL36',LINKEDASSIGNMENT::string ,'COL37',LINKEDPROJECT::string ,'COL38',LINKEDTASK::string ,'COL39',LINKEDTIME::string)::string )::BINARY as BIW_MD5_KEY

FROM     
ASSIGNMENTTIMEPHASEDDATASET  STG 

CROSS JOIN FISCAL_WEEK FSC_WK
