/*---------------------------------------------------------------------------
Command to run model:
-- dbt run --select ETL_ODS_NPD_MSPROJECTS_ASSIGNMENTS_WEEKLY_SNAPSHOT 
-- dbt build --full-refresh --select ETL_ODS_NPD_MSPROJECTS_ASSIGNMENTS_WEEKLY_SNAPSHOT 
pk: AssignmentId ,ProjectId 
Version     Date            Author              Description
-------     --------        -----------         ----------------------------------
1.0         25-JAN-2023     KALI DANDAPANI      Initial Version
---------------------------------------------------------------------------*/

{################# EDW Job Template Variables #################}
{%-set v_pk_list = ['AssignmentId' ,'ProjectId']-%}

{################# Batch control insert and update SQL #################}
{%- set v_dbt_job_name = 'DBT_ETL_ODS_NPD_MSPROJECTS_ASSIGNMENTS_WEEKLY_SNAPSHOT'-%}
-- Step 1 Batch process info
{%- set v_watermark = edw_batch_control(v_dbt_job_name,config.get('schema'),config.get('alias') ,config.get('tags'),config.get('materialized') ) -%}
{%- set V_LWM = v_watermark[0] -%}
{%- set V_HWM = v_watermark[1] -%}
{%- set V_START_DTTM = v_watermark[2] -%}
{%- set V_BIW_BATCH_ID = v_watermark[3] -%}
{%- set v_sql_upd_success_batch = "CALL UTILITY.EDW_BATCH_SUCCESS_PROC('"~v_dbt_job_name~"')" -%}

{################# Snowflake Object Configuration #################}
{{
    config(
         description = 'Building ETL table ASSIGNMENTS_WEEKLY_SNAPSHOT for NPD LANDING PROJECT'
        ,transient=true   
        ,materialized='table'
        ,schema ='ETL_ODS_NPD'
        ,alias= 'MSPROJECTS_ASSIGNMENTS_WEEKLY_SNAPSHOT'
        ,tags =['ODS_NPD']
        ,post_hook= [v_sql_upd_success_batch]	
        )
}}

WITH FISCAL_WEEK AS 
(
    SELECT 
        DISTINCT FISCAL_WEEK_KEY
    FROM 
    {{ref('MART_DATE') }}
    WHERE 
        CALENDAR_DATE = (CURRENT_TIMESTAMP() - INTERVAL '7 HOUR')::DATE
        or CALENDAR_DATE = (CURRENT_TIMESTAMP() )::DATE
)

,ASSIGNMENTS AS (
SELECT ASSIGNMENTID
, PROJECTID
, ASSIGNMENTACTUALCOST
, ASSIGNMENTACTUALFINISHDATE
, ASSIGNMENTACTUALOVERTIMECOST
, ASSIGNMENTACTUALOVERTIMEWORK
, ASSIGNMENTACTUALREGULARCOST
, ASSIGNMENTACTUALREGULARWORK
, ASSIGNMENTACTUALSTARTDATE
, ASSIGNMENTACTUALWORK
, ASSIGNMENTACWP
, ASSIGNMENTALLUPDATESAPPLIED
, ASSIGNMENTBCWP
, ASSIGNMENTBCWS
, ASSIGNMENTBOOKINGDESCRIPTION
, ASSIGNMENTBOOKINGID
, ASSIGNMENTBOOKINGNAME
, ASSIGNMENTBUDGETCOST
, ASSIGNMENTBUDGETMATERIALWORK
, ASSIGNMENTBUDGETWORK
, ASSIGNMENTCOST
, ASSIGNMENTCOSTVARIANCE
, ASSIGNMENTCREATEDDATE
, ASSIGNMENTCREATEDREVISIONCOUNTER
, ASSIGNMENTCV
, ASSIGNMENTDELAY
, ASSIGNMENTFINISHDATE
, ASSIGNMENTFINISHVARIANCE
, ASSIGNMENTISOVERALLOCATED
, ASSIGNMENTISPUBLISHED
, ASSIGNMENTMATERIALACTUALWORK
, ASSIGNMENTMATERIALWORK
, ASSIGNMENTMODIFIEDDATE
, ASSIGNMENTMODIFIEDREVISIONCOUNTER
, ASSIGNMENTOVERTIMECOST
, ASSIGNMENTOVERTIMEWORK
, ASSIGNMENTPEAKUNITS
, ASSIGNMENTPERCENTWORKCOMPLETED
, ASSIGNMENTREGULARCOST
, ASSIGNMENTREGULARWORK
, ASSIGNMENTREMAININGCOST
, ASSIGNMENTREMAININGOVERTIMECOST
, ASSIGNMENTREMAININGOVERTIMEWORK
, ASSIGNMENTREMAININGREGULARCOST
, ASSIGNMENTREMAININGREGULARWORK
, ASSIGNMENTREMAININGWORK
, ASSIGNMENTRESOURCEPLANWORK
, ASSIGNMENTRESOURCETYPE
, ASSIGNMENTSTARTDATE
, ASSIGNMENTSTARTVARIANCE
, ASSIGNMENTSV
, ASSIGNMENTTYPE
, ASSIGNMENTUPDATESAPPLIEDDATE
, ASSIGNMENTVAC
, ASSIGNMENTWORK
, ASSIGNMENTWORKVARIANCE
, COSTTYPE_R
, DETECTABILITY_T
, FLAGSTATUS_T
, HEALTH_T
, IMPACT_T
, ISPUBLIC
, MITIGATIONFLAG_T
, NPDGATE_T
, NPDMILESTONE_T
, PROBABILITY_T
, PROJECTNAME
, RBS_R
, RESOURCEDEPARTMENTS_R
, RESOURCEID
, RESOURCENAME
, RISKFLAG_T
, RISKLEVEL_T
, RISKSCORE_T
, RISK_T
, ROLE_R
, TASKID
, TASKISACTIVE
, TASKNAME
, TIMESHEETCLASSID
, TYPEDESCRIPTION
, TYPENAME
, LINKEDBASELINE
, LINKEDPROJECT
, LINKEDRESOURCE
, LINKEDTASK
, LINKEDTIMEPHASEDDATA
, BIW_INS_DTTM
, BIW_UPD_DTTM
FROM 
    {{source ('STG_NPD_MSPROJECTS_ODATAV1','ASSIGNMENTS')}}  
    QUALIFY( ROW_NUMBER() OVER (PARTITION BY AssignmentId ,ProjectId   ORDER BY BIW_UPD_DTTM DESC) =1)
)

SELECT 
    MD5(OBJECT_CONSTRUCT (  'COL1',FSC_WK.FISCAL_WEEK_KEY::STRING
                            ,'COL2',STG.ASSIGNMENTID::STRING
                            ,'COL3',STG.ProjectId::STRING 
                         )::STRING 
        )::BINARY AS ASSIGNMENTS_KEY 
    ,FSC_WK.FISCAL_WEEK_KEY AS SNAPSHOT_WEEK_KEY
    ,ASSIGNMENTID
, STG.PROJECTID
, STG.ASSIGNMENTACTUALCOST
, STG.ASSIGNMENTACTUALFINISHDATE
, STG.ASSIGNMENTACTUALOVERTIMECOST
, STG.ASSIGNMENTACTUALOVERTIMEWORK
, STG.ASSIGNMENTACTUALREGULARCOST
, STG.ASSIGNMENTACTUALREGULARWORK
, STG.ASSIGNMENTACTUALSTARTDATE
, STG.ASSIGNMENTACTUALWORK
, STG.ASSIGNMENTACWP
, STG.ASSIGNMENTALLUPDATESAPPLIED
, STG.ASSIGNMENTBCWP
, STG.ASSIGNMENTBCWS
, STG.ASSIGNMENTBOOKINGDESCRIPTION
, STG.ASSIGNMENTBOOKINGID
, STG.ASSIGNMENTBOOKINGNAME
, STG.ASSIGNMENTBUDGETCOST
, STG.ASSIGNMENTBUDGETMATERIALWORK
, STG.ASSIGNMENTBUDGETWORK
, STG.ASSIGNMENTCOST
, STG.ASSIGNMENTCOSTVARIANCE
, STG.ASSIGNMENTCREATEDDATE
, STG.ASSIGNMENTCREATEDREVISIONCOUNTER
, STG.ASSIGNMENTCV
, STG.ASSIGNMENTDELAY
, STG.ASSIGNMENTFINISHDATE
, STG.ASSIGNMENTFINISHVARIANCE
, STG.ASSIGNMENTISOVERALLOCATED
, STG.ASSIGNMENTISPUBLISHED
, STG.ASSIGNMENTMATERIALACTUALWORK
, STG.ASSIGNMENTMATERIALWORK
, STG.ASSIGNMENTMODIFIEDDATE
, STG.ASSIGNMENTMODIFIEDREVISIONCOUNTER
, STG.ASSIGNMENTOVERTIMECOST
, STG.ASSIGNMENTOVERTIMEWORK
, STG.ASSIGNMENTPEAKUNITS
, STG.ASSIGNMENTPERCENTWORKCOMPLETED
, STG.ASSIGNMENTREGULARCOST
, STG.ASSIGNMENTREGULARWORK
, STG.ASSIGNMENTREMAININGCOST
, STG.ASSIGNMENTREMAININGOVERTIMECOST
, STG.ASSIGNMENTREMAININGOVERTIMEWORK
, STG.ASSIGNMENTREMAININGREGULARCOST
, STG.ASSIGNMENTREMAININGREGULARWORK
, STG.ASSIGNMENTREMAININGWORK
, STG.ASSIGNMENTRESOURCEPLANWORK
, STG.ASSIGNMENTRESOURCETYPE
, STG.ASSIGNMENTSTARTDATE
, STG.ASSIGNMENTSTARTVARIANCE
, STG.ASSIGNMENTSV
, STG.ASSIGNMENTTYPE
, STG.ASSIGNMENTUPDATESAPPLIEDDATE
, STG.ASSIGNMENTVAC
, STG.ASSIGNMENTWORK
, STG.ASSIGNMENTWORKVARIANCE
, STG.COSTTYPE_R
, STG.DETECTABILITY_T
, STG.FLAGSTATUS_T
, STG.HEALTH_T
, STG.IMPACT_T
, STG.ISPUBLIC
, STG.MITIGATIONFLAG_T
, STG.NPDGATE_T
, STG.NPDMILESTONE_T
, STG.PROBABILITY_T
, STG.PROJECTNAME
, STG.RBS_R
, STG.RESOURCEDEPARTMENTS_R
, STG.RESOURCEID
, STG.RESOURCENAME
, STG.RISKFLAG_T
, STG.RISKLEVEL_T
, STG.RISKSCORE_T
, STG.RISK_T
, STG.ROLE_R
, STG.TASKID
, STG.TASKISACTIVE
, STG.TASKNAME
, STG.TIMESHEETCLASSID
, STG.TYPEDESCRIPTION
, STG.TYPENAME
, STG.LINKEDBASELINE
, STG.LINKEDPROJECT
, STG.LINKEDRESOURCE
, STG.LINKEDTASK
,STG.LINKEDTIMEPHASEDDATA
,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_INS_DTTM 
,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_UPD_DTTM 
,{{V_BIW_BATCH_ID}}::NUMBER as BIW_BATCH_ID 
,md5(object_construct ('COL1',ASSIGNMENTID::string ,'COL2',PROJECTID::string ,'COL3',ASSIGNMENTACTUALCOST::string ,'COL4',ASSIGNMENTACTUALFINISHDATE::string ,'COL5',ASSIGNMENTACTUALOVERTIMECOST::string ,'COL6',ASSIGNMENTACTUALOVERTIMEWORK::string ,'COL7',ASSIGNMENTACTUALREGULARCOST::string ,'COL8',ASSIGNMENTACTUALREGULARWORK::string ,'COL9',ASSIGNMENTACTUALSTARTDATE::string ,'COL10',ASSIGNMENTACTUALWORK::string ,'COL11',ASSIGNMENTACWP::string ,'COL12',ASSIGNMENTALLUPDATESAPPLIED::string ,'COL13',ASSIGNMENTBCWP::string ,'COL14',ASSIGNMENTBCWS::string ,'COL15',ASSIGNMENTBOOKINGDESCRIPTION::string ,'COL16',ASSIGNMENTBOOKINGID::string ,'COL17',ASSIGNMENTBOOKINGNAME::string ,'COL18',ASSIGNMENTBUDGETCOST::string ,'COL19',ASSIGNMENTBUDGETMATERIALWORK::string ,'COL20',ASSIGNMENTBUDGETWORK::string ,'COL21',ASSIGNMENTCOST::string ,'COL22',ASSIGNMENTCOSTVARIANCE::string ,'COL23',ASSIGNMENTCREATEDDATE::string ,'COL24',ASSIGNMENTCREATEDREVISIONCOUNTER::string ,'COL25',ASSIGNMENTCV::string ,'COL26',ASSIGNMENTDELAY::string ,'COL27',ASSIGNMENTFINISHDATE::string ,'COL28',ASSIGNMENTFINISHVARIANCE::string ,'COL29',ASSIGNMENTISOVERALLOCATED::string ,'COL30',ASSIGNMENTISPUBLISHED::string ,'COL31',ASSIGNMENTMATERIALACTUALWORK::string ,'COL32',ASSIGNMENTMATERIALWORK::string ,'COL33',ASSIGNMENTMODIFIEDDATE::string ,'COL34',ASSIGNMENTMODIFIEDREVISIONCOUNTER::string ,'COL35',ASSIGNMENTOVERTIMECOST::string ,'COL36',ASSIGNMENTOVERTIMEWORK::string ,'COL37',ASSIGNMENTPEAKUNITS::string ,'COL38',ASSIGNMENTPERCENTWORKCOMPLETED::string ,'COL39',ASSIGNMENTREGULARCOST::string ,'COL40',ASSIGNMENTREGULARWORK::string ,'COL41',ASSIGNMENTREMAININGCOST::string ,'COL42',ASSIGNMENTREMAININGOVERTIMECOST::string ,'COL43',ASSIGNMENTREMAININGOVERTIMEWORK::string ,'COL44',ASSIGNMENTREMAININGREGULARCOST::string ,'COL45',ASSIGNMENTREMAININGREGULARWORK::string ,'COL46',ASSIGNMENTREMAININGWORK::string ,'COL47',ASSIGNMENTRESOURCEPLANWORK::string ,'COL48',ASSIGNMENTRESOURCETYPE::string ,'COL49',ASSIGNMENTSTARTDATE::string ,'COL50',ASSIGNMENTSTARTVARIANCE::string ,'COL51',ASSIGNMENTSV::string ,'COL52',ASSIGNMENTTYPE::string ,'COL53',ASSIGNMENTUPDATESAPPLIEDDATE::string ,'COL54',ASSIGNMENTVAC::string ,'COL55',ASSIGNMENTWORK::string ,'COL56',ASSIGNMENTWORKVARIANCE::string ,'COL57',COSTTYPE_R::string ,'COL58',DETECTABILITY_T::string ,'COL59',FLAGSTATUS_T::string ,'COL60',HEALTH_T::string ,'COL61',IMPACT_T::string ,'COL62',ISPUBLIC::string ,'COL63',MITIGATIONFLAG_T::string ,'COL64',NPDGATE_T::string ,'COL65',NPDMILESTONE_T::string ,'COL66',PROBABILITY_T::string ,'COL67',PROJECTNAME::string ,'COL68',RBS_R::string ,'COL69',RESOURCEDEPARTMENTS_R::string ,'COL70',RESOURCEID::string ,'COL71',RESOURCENAME::string ,'COL72',RISKFLAG_T::string ,'COL73',RISKLEVEL_T::string ,'COL74',RISKSCORE_T::string ,'COL75',RISK_T::string ,'COL76',ROLE_R::string ,'COL77',TASKID::string ,'COL78',TASKISACTIVE::string ,'COL79',TASKNAME::string ,'COL80',TIMESHEETCLASSID::string ,'COL81',TYPEDESCRIPTION::string ,'COL82',TYPENAME::string ,'COL83',LINKEDBASELINE::string ,'COL84',LINKEDPROJECT::string ,'COL85',LINKEDRESOURCE::string ,'COL86',LINKEDTASK::string ,'COL87',LINKEDTIMEPHASEDDATA::string )::string )::BINARY as BIW_MD5_KEY

FROM     
ASSIGNMENTS  STG 

CROSS JOIN FISCAL_WEEK FSC_WK
