/*---------------------------------------------------------------------------
Command to run model:
-- dbt run --select ETL_ODS_NPD_MSPROJECTS_PRIORITIZATIONS_WEEKLY_SNAPSHOT 
-- dbt build --full-refresh --select ETL_ODS_NPD_MSPROJECTS_PRIORITIZATIONS_WEEKLY_SNAPSHOT 

Version     Date            Author              Description
-------     --------        -----------         ----------------------------------
1.0         25-JAN-2023     KALI DANDAPANI      Initial Version
---------------------------------------------------------------------------*/

{################# EDW Job Template Variables #################}
{%-set v_pk_list = ['PRIORITIZATIONID']-%}

{################# Batch control insert and update SQL #################}
{%- set v_dbt_job_name = 'DBT_ETL_ODS_NPD_MSPROJECTS_PRIORITIZATIONS_WEEKLY_SNAPSHOT'-%}
-- Step 1 Batch process info
{%- set v_watermark = edw_batch_control(v_dbt_job_name,config.get('schema'),config.get('alias') ,config.get('tags'),config.get('materialized') ) -%}
{%- set V_LWM = v_watermark[0] -%}
{%- set V_HWM = v_watermark[1] -%}
{%- set V_START_DTTM = v_watermark[2] -%}
{%- set V_BIW_BATCH_ID = v_watermark[3] -%}
{%- set v_sql_upd_success_batch = "CALL UTILITY.EDW_BATCH_SUCCESS_PROC('"~v_dbt_job_name~"')" -%}

{################# Snowflake Object Configuration #################}
{{
    config(
         description = 'Building ETL table PRIORITIZATIONS_WEEKLY_SNAPSHOT for NPD LANDING PROJECT'
        ,transient=true   
        ,materialized='table'
        ,schema ='ETL_ODS_NPD'
        ,alias= 'MSPROJECTS_PRIORITIZATIONS_WEEKLY_SNAPSHOT'
        ,tags =['ODS_NPD']
        ,post_hook= [v_sql_upd_success_batch]	
        )
}}

WITH FISCAL_WEEK AS 
(
    SELECT 
        DISTINCT FISCAL_WEEK_KEY
    FROM 
    {{ref('MART_DATE') }}
    WHERE 
        CALENDAR_DATE = (CURRENT_TIMESTAMP() - INTERVAL '7 HOUR')::DATE
        or CALENDAR_DATE = (CURRENT_TIMESTAMP() )::DATE
)

,PRIORITIZATIONS AS (
SELECT PRIORITIZATIONID
, CONSISTENCYRATIO
, CREATEDBYRESOURCEID
, CREATEDBYRESOURCENAME
, DEPARTMENTID
, DEPARTMENTNAME
, MODIFIEDBYRESOURCEID
, MODIFIEDBYRESOURCENAME
, PRIORITIZATIONCREATEDDATE
, PRIORITIZATIONDESCRIPTION
, PRIORITIZATIONISMANUAL
, PRIORITIZATIONMODIFIEDDATE
, PRIORITIZATIONNAME
, LINKEDCREATEDBYRESOURCE
, LINKEDMODIFIEDBYRESOURCE
, LINKEDPRIORITIZATIONDRIVERRELATIONS
, LINKEDPRIORITIZATIONDRIVERS
, BIW_INS_DTTM
, BIW_UPD_DTTM
FROM 
    {{source ('STG_NPD_MSPROJECTS_ODATAV1','PRIORITIZATIONS')}}  
    QUALIFY( ROW_NUMBER() OVER (PARTITION BY PRIORITIZATIONID  ORDER BY BIW_UPD_DTTM DESC) =1)
)

SELECT 
    MD5(OBJECT_CONSTRUCT (  'COL1',FSC_WK.FISCAL_WEEK_KEY::STRING
                            ,'COL2',STG.PRIORITIZATIONID::STRING
                         )::STRING 
        )::BINARY AS PRIORITIZATIONS_KEY 
    ,FSC_WK.FISCAL_WEEK_KEY AS SNAPSHOT_WEEK_KEY
    ,PRIORITIZATIONID
, STG.CONSISTENCYRATIO
, STG.CREATEDBYRESOURCEID
, STG.CREATEDBYRESOURCENAME
, STG.DEPARTMENTID
, STG.DEPARTMENTNAME
, STG.MODIFIEDBYRESOURCEID
, STG.MODIFIEDBYRESOURCENAME
, STG.PRIORITIZATIONCREATEDDATE
, STG.PRIORITIZATIONDESCRIPTION
, STG.PRIORITIZATIONISMANUAL
, STG.PRIORITIZATIONMODIFIEDDATE
, STG.PRIORITIZATIONNAME
, STG.LINKEDCREATEDBYRESOURCE
, STG.LINKEDMODIFIEDBYRESOURCE
, STG.LINKEDPRIORITIZATIONDRIVERRELATIONS
,STG.LINKEDPRIORITIZATIONDRIVERS
,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_INS_DTTM 
    ,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_UPD_DTTM 
   ,{{V_BIW_BATCH_ID}}::NUMBER as BIW_BATCH_ID
    ,md5(object_construct ('COL1',PRIORITIZATIONID::string ,'COL2',CONSISTENCYRATIO::string ,'COL3',CREATEDBYRESOURCEID::string ,'COL4',CREATEDBYRESOURCENAME::string ,'COL5',DEPARTMENTID::string ,'COL6',DEPARTMENTNAME::string ,'COL7',MODIFIEDBYRESOURCEID::string ,'COL8',MODIFIEDBYRESOURCENAME::string ,'COL9',PRIORITIZATIONCREATEDDATE::string ,'COL10',PRIORITIZATIONDESCRIPTION::string ,'COL11',PRIORITIZATIONISMANUAL::string ,'COL12',PRIORITIZATIONMODIFIEDDATE::string ,'COL13',PRIORITIZATIONNAME::string ,'COL14',LINKEDCREATEDBYRESOURCE::string ,'COL15',LINKEDMODIFIEDBYRESOURCE::string ,'COL16',LINKEDPRIORITIZATIONDRIVERRELATIONS::string ,'COL17',LINKEDPRIORITIZATIONDRIVERS::string )::string )::BINARY as BIW_MD5_KEY

FROM     
PRIORITIZATIONS  STG 

CROSS JOIN FISCAL_WEEK FSC_WK
