
/*---------------------------------------------------------------------------
Command to run model:
-- dbt run --select ETL_ODS_NPD_MSPROJECTS_PROJECTBASELINES_WEEKLY_SNAPSHOT 
-- dbt build --full-refresh --select ETL_ODS_NPD_MSPROJECTS_PROJECTBASELINES_WEEKLY_SNAPSHOT 

Version     Date            Author              Description
-------     --------        -----------         ----------------------------------
1.0         25-JAN-2023     KALI DANDAPANI      Initial Version
---------------------------------------------------------------------------*/

{################# EDW Job Template Variables #################}
{%-set v_pk_list = ['BASELINENUMBER','PROJECTID']-%}

{################# Batch control insert and update SQL #################}
{%- set v_dbt_job_name = 'DBT_ETL_ODS_NPD_MSPROJECTS_PROJECTBASELINES_WEEKLY_SNAPSHOT'-%}
-- Step 1 Batch process info
{%- set v_watermark = edw_batch_control(v_dbt_job_name,config.get('schema'),config.get('alias') ,config.get('tags'),config.get('materialized') ) -%}
{%- set V_LWM = v_watermark[0] -%}
{%- set V_HWM = v_watermark[1] -%}
{%- set V_START_DTTM = v_watermark[2] -%}
{%- set V_BIW_BATCH_ID = v_watermark[3] -%}
{%- set v_sql_upd_success_batch = "CALL UTILITY.EDW_BATCH_SUCCESS_PROC('"~v_dbt_job_name~"')" -%}

{################# Snowflake Object Configuration #################}
{{
    config(
         description = 'Building ETL table PROJECTBASELINES_WEEKLY_SNAPSHOT for NPD LANDING PROJECT'
        ,transient=true   
        ,materialized='table'
        ,schema ='ETL_ODS_NPD'
        ,alias= 'MSPROJECTS_PROJECTBASELINES_WEEKLY_SNAPSHOT'
        ,tags =['ODS_NPD']
        ,post_hook= [v_sql_upd_success_batch]	
        )
}}

WITH FISCAL_WEEK AS 
(
    SELECT 
        DISTINCT FISCAL_WEEK_KEY
    FROM 
    {{ref('MART_DATE') }}
    WHERE 
        CALENDAR_DATE = (CURRENT_TIMESTAMP() - INTERVAL '7 HOUR')::DATE
        or CALENDAR_DATE = (CURRENT_TIMESTAMP() )::DATE
)

,PROJECTBASELINES AS (
SELECT BASELINENUMBER
, PROJECTID
, PROJECTBASELINEBUDGETCOST
, PROJECTBASELINEBUDGETWORK
, PROJECTBASELINECOST
, PROJECTBASELINEDELIVERABLEFINISHDATE
, PROJECTBASELINEDELIVERABLESTARTDATE
, PROJECTBASELINEDURATION
, PROJECTBASELINEDURATIONSTRING
, PROJECTBASELINEFINISHDATE
, PROJECTBASELINEFINISHDATESTRING
, PROJECTBASELINEFIXEDCOST
, PROJECTBASELINEMODIFIEDDATE
, PROJECTBASELINESTARTDATE
, PROJECTBASELINESTARTDATESTRING
, PROJECTBASELINEWORK
, PROJECTNAME
, TASKID
, LINKEDPROJECT
, BIW_INS_DTTM
, BIW_UPD_DTTM
FROM 
    {{source ('STG_NPD_MSPROJECTS_ODATAV1','PROJECTBASELINES')}}  
    QUALIFY( ROW_NUMBER() OVER (PARTITION BY BASELINENUMBER,PROJECTID  ORDER BY BIW_UPD_DTTM DESC) =1)
)

SELECT 
    MD5(OBJECT_CONSTRUCT (  'COL1',FSC_WK.FISCAL_WEEK_KEY::STRING
                            ,'COL2',STG.BASELINENUMBER::STRING
                            ,'COL3',STG.PROJECTID::STRING
                         )::STRING 
        )::BINARY AS PROJECTBASELINES_KEY 
    ,FSC_WK.FISCAL_WEEK_KEY AS SNAPSHOT_WEEK_KEY
    ,BASELINENUMBER
, STG.PROJECTID
, STG.PROJECTBASELINEBUDGETCOST
, STG.PROJECTBASELINEBUDGETWORK
, STG.PROJECTBASELINECOST
, STG.PROJECTBASELINEDELIVERABLEFINISHDATE
, STG.PROJECTBASELINEDELIVERABLESTARTDATE
, STG.PROJECTBASELINEDURATION
, STG.PROJECTBASELINEDURATIONSTRING
, STG.PROJECTBASELINEFINISHDATE
, STG.PROJECTBASELINEFINISHDATESTRING
, STG.PROJECTBASELINEFIXEDCOST
, STG.PROJECTBASELINEMODIFIEDDATE
, STG.PROJECTBASELINESTARTDATE
, STG.PROJECTBASELINESTARTDATESTRING
, STG.PROJECTBASELINEWORK
, STG.PROJECTNAME
, STG.TASKID
,STG.LINKEDPROJECT
,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_INS_DTTM 
    ,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_UPD_DTTM 
   ,{{V_BIW_BATCH_ID}}::NUMBER as BIW_BATCH_ID 
   ,md5(object_construct ('COL1',BASELINENUMBER::string ,'COL2',PROJECTID::string ,'COL3',PROJECTBASELINEBUDGETCOST::string ,'COL4',PROJECTBASELINEBUDGETWORK::string ,'COL5',PROJECTBASELINECOST::string ,'COL6',PROJECTBASELINEDELIVERABLEFINISHDATE::string ,'COL7',PROJECTBASELINEDELIVERABLESTARTDATE::string ,'COL8',PROJECTBASELINEDURATION::string ,'COL9',PROJECTBASELINEDURATIONSTRING::string ,'COL10',PROJECTBASELINEFINISHDATE::string ,'COL11',PROJECTBASELINEFINISHDATESTRING::string ,'COL12',PROJECTBASELINEFIXEDCOST::string ,'COL13',PROJECTBASELINEMODIFIEDDATE::string ,'COL14',PROJECTBASELINESTARTDATE::string ,'COL15',PROJECTBASELINESTARTDATESTRING::string ,'COL16',PROJECTBASELINEWORK::string ,'COL17',PROJECTNAME::string ,'COL18',TASKID::string ,'COL19',LINKEDPROJECT::string )::string )::BINARY as BIW_MD5_KEY

FROM     
PROJECTBASELINES  STG 

CROSS JOIN FISCAL_WEEK FSC_WK
