
/*---------------------------------------------------------------------------
Command to run model:
-- dbt run --select ETL_ODS_NPD_MSPROJECTS_TASKS_WEEKLY_SNAPSHOT 
-- dbt build --full-refresh --select ETL_ODS_NPD_MSPROJECTS_TASKS_WEEKLY_SNAPSHOT 

Version     Date            Author              Description
-------     --------        -----------         ----------------------------------
1.0         25-JAN-2023     KALI DANDAPANI      Initial Version
---------------------------------------------------------------------------*/

{################# EDW Job Template Variables #################}
{%-set v_pk_list = ['PROJECTID','TASKID']-%}

{################# Batch control insert and update SQL #################}
{%- set v_dbt_job_name = 'DBT_ETL_ODS_NPD_MSPROJECTS_TASKS_WEEKLY_SNAPSHOT'-%}
-- Step 1 Batch process info
{%- set v_watermark = edw_batch_control(v_dbt_job_name,config.get('schema'),config.get('alias') ,config.get('tags'),config.get('materialized') ) -%}
{%- set V_LWM = v_watermark[0] -%}
{%- set V_HWM = v_watermark[1] -%}
{%- set V_START_DTTM = v_watermark[2] -%}
{%- set V_BIW_BATCH_ID = v_watermark[3] -%}
{%- set v_sql_upd_success_batch = "CALL UTILITY.EDW_BATCH_SUCCESS_PROC('"~v_dbt_job_name~"')" -%}

{################# Snowflake Object Configuration #################}
{{
    config(
         description = 'Building ETL table TASKS_WEEKLY_SNAPSHOT for NPD LANDING PROJECT'
        ,transient=true   
        ,materialized='table'
        ,schema ='ETL_ODS_NPD'
        ,alias= 'MSPROJECTS_TASKS_WEEKLY_SNAPSHOT'
        ,tags =['ODS_NPD']
        ,post_hook= [v_sql_upd_success_batch]	
        )
}}

WITH FISCAL_WEEK AS 
(
    SELECT 
        DISTINCT FISCAL_WEEK_KEY
    FROM 
    {{ref('MART_DATE') }}
    WHERE 
        CALENDAR_DATE = (CURRENT_TIMESTAMP() - INTERVAL '7 HOUR')::DATE
        or CALENDAR_DATE = (CURRENT_TIMESTAMP() )::DATE
)

,TASKS AS (
SELECT PROJECTID
, TASKID
, DETECTABILITY
, FLAGSTATUS
, HEALTH
, IMPACT
, MITIGATIONFLAG
, NPDGATE
, NPDMILESTONE
, PARENTTASKID
, PARENTTASKNAME
, PROBABILITY
, PROJECTNAME
, RISK
, RISKFLAG
, RISKLEVEL
, RISKSCORE
, TASKACTUALCOST
, TASKACTUALDURATION
, TASKACTUALFINISHDATE
, TASKACTUALFIXEDCOST
, TASKACTUALOVERTIMECOST
, TASKACTUALOVERTIMEWORK
, TASKACTUALREGULARCOST
, TASKACTUALREGULARWORK
, TASKACTUALSTARTDATE
, TASKACTUALWORK
, TASKACWP
, TASKBCWP
, TASKBCWS
, TASKBUDGETCOST
, TASKBUDGETWORK
, TASKCLIENTUNIQUEID
, TASKCOST
, TASKCOSTVARIANCE
, TASKCPI
, TASKCREATEDDATE
, TASKCREATEDREVISIONCOUNTER
, TASKCV
, TASKCVP
, TASKDEADLINE
, TASKDELIVERABLEFINISHDATE
, TASKDELIVERABLESTARTDATE
, TASKDURATION
, TASKDURATIONISESTIMATED
, TASKDURATIONSTRING
, TASKDURATIONVARIANCE
, TASKEAC
, TASKEARLYFINISH
, TASKEARLYSTART
, TASKFINISHDATE
, TASKFINISHDATESTRING
, TASKFINISHVARIANCE
, TASKFIXEDCOST
, TASKFIXEDCOSTASSIGNMENTID
, TASKFREESLACK
, TASKHYPERLINKADDRESS
, TASKHYPERLINKFRIENDLYNAME
, TASKHYPERLINKSUBADDRESS
, TASKIGNORESRESOURCECALENDAR
, TASKINDEX
, TASKISACTIVE
, TASKISCRITICAL
, TASKISEFFORTDRIVEN
, TASKISEXTERNAL
, TASKISMANUALLYSCHEDULED
, TASKISMARKED
, TASKISMILESTONE
, TASKISOVERALLOCATED
, TASKISPROJECTSUMMARY
, TASKISRECURRING
, TASKISSUMMARY
, TASKLATEFINISH
, TASKLATESTART
, TASKLEVELINGDELAY
, TASKMODIFIEDDATE
, TASKMODIFIEDREVISIONCOUNTER
, TASKNAME
, TASKOUTLINELEVEL
, TASKOUTLINENUMBER
, TASKOVERTIMECOST
, TASKOVERTIMEWORK
, TASKPERCENTCOMPLETED
, TASKPERCENTWORKCOMPLETED
, TASKPHYSICALPERCENTCOMPLETED
, TASKPRIORITY
, TASKREGULARCOST
, TASKREGULARWORK
, TASKREMAININGCOST
, TASKREMAININGDURATION
, TASKREMAININGOVERTIMECOST
, TASKREMAININGOVERTIMEWORK
, TASKREMAININGREGULARCOST
, TASKREMAININGREGULARWORK
, TASKREMAININGWORK
, TASKRESOURCEPLANWORK
, TASKSPI
, TASKSTARTDATE
, TASKSTARTDATESTRING
, TASKSTARTVARIANCE
, TASKSTATUSMANAGERUID
, TASKSV
, TASKSVP
, TASKTCPI
, TASKTOTALSLACK
, TASKVAC
, TASKWBS
, TASKWORK
, TASKWORKVARIANCE
, LINKEDASSIGNMENTS
, LINKEDASSIGNMENTSBASELINES
, LINKEDASSIGNMENTSBASELINETIMEPHASEDDATA
, LINKEDBASELINES
, LINKEDBASELINESTIMEPHASEDDATASET
, LINKEDISSUES
, LINKEDPROJECT
, LINKEDRISKS
, LINKEDTIMEPHASEDINFO
, BIW_INS_DTTM
, BIW_UPD_DTTM
FROM 
    {{source ('STG_NPD_MSPROJECTS_ODATAV1','TASKS')}}  
    QUALIFY( ROW_NUMBER() OVER (PARTITION BY PROJECTID,TASKID  ORDER BY BIW_UPD_DTTM DESC) =1)
)

SELECT 
    MD5(OBJECT_CONSTRUCT (  'COL1',FSC_WK.FISCAL_WEEK_KEY::STRING
                            ,'COL2',STG.PROJECTID::STRING
                            ,'COL3',STG.TASKID::STRING
                         )::STRING 
        )::BINARY AS TASKS_KEY 
    ,FSC_WK.FISCAL_WEEK_KEY AS SNAPSHOT_WEEK_KEY
    ,PROJECTID
, STG.TASKID
, STG.DETECTABILITY
, STG.FLAGSTATUS
, STG.HEALTH
, STG.IMPACT
, STG.MITIGATIONFLAG
, STG.NPDGATE
, STG.NPDMILESTONE
, STG.PARENTTASKID
, STG.PARENTTASKNAME
, STG.PROBABILITY
, STG.PROJECTNAME
, STG.RISK
, STG.RISKFLAG
, STG.RISKLEVEL
, STG.RISKSCORE
, STG.TASKACTUALCOST
, STG.TASKACTUALDURATION
, STG.TASKACTUALFINISHDATE
, STG.TASKACTUALFIXEDCOST
, STG.TASKACTUALOVERTIMECOST
, STG.TASKACTUALOVERTIMEWORK
, STG.TASKACTUALREGULARCOST
, STG.TASKACTUALREGULARWORK
, STG.TASKACTUALSTARTDATE
, STG.TASKACTUALWORK
, STG.TASKACWP
, STG.TASKBCWP
, STG.TASKBCWS
, STG.TASKBUDGETCOST
, STG.TASKBUDGETWORK
, STG.TASKCLIENTUNIQUEID
, STG.TASKCOST
, STG.TASKCOSTVARIANCE
, STG.TASKCPI
, STG.TASKCREATEDDATE
, STG.TASKCREATEDREVISIONCOUNTER
, STG.TASKCV
, STG.TASKCVP
, STG.TASKDEADLINE
, STG.TASKDELIVERABLEFINISHDATE
, STG.TASKDELIVERABLESTARTDATE
, STG.TASKDURATION
, STG.TASKDURATIONISESTIMATED
, STG.TASKDURATIONSTRING
, STG.TASKDURATIONVARIANCE
, STG.TASKEAC
, STG.TASKEARLYFINISH
, STG.TASKEARLYSTART
, STG.TASKFINISHDATE
, STG.TASKFINISHDATESTRING
, STG.TASKFINISHVARIANCE
, STG.TASKFIXEDCOST
, STG.TASKFIXEDCOSTASSIGNMENTID
, STG.TASKFREESLACK
, STG.TASKHYPERLINKADDRESS
, STG.TASKHYPERLINKFRIENDLYNAME
, STG.TASKHYPERLINKSUBADDRESS
, STG.TASKIGNORESRESOURCECALENDAR
, STG.TASKINDEX
, STG.TASKISACTIVE
, STG.TASKISCRITICAL
, STG.TASKISEFFORTDRIVEN
, STG.TASKISEXTERNAL
, STG.TASKISMANUALLYSCHEDULED
, STG.TASKISMARKED
, STG.TASKISMILESTONE
, STG.TASKISOVERALLOCATED
, STG.TASKISPROJECTSUMMARY
, STG.TASKISRECURRING
, STG.TASKISSUMMARY
, STG.TASKLATEFINISH
, STG.TASKLATESTART
, STG.TASKLEVELINGDELAY
, STG.TASKMODIFIEDDATE
, STG.TASKMODIFIEDREVISIONCOUNTER
, STG.TASKNAME
, STG.TASKOUTLINELEVEL
, STG.TASKOUTLINENUMBER
, STG.TASKOVERTIMECOST
, STG.TASKOVERTIMEWORK
, STG.TASKPERCENTCOMPLETED
, STG.TASKPERCENTWORKCOMPLETED
, STG.TASKPHYSICALPERCENTCOMPLETED
, STG.TASKPRIORITY
, STG.TASKREGULARCOST
, STG.TASKREGULARWORK
, STG.TASKREMAININGCOST
, STG.TASKREMAININGDURATION
, STG.TASKREMAININGOVERTIMECOST
, STG.TASKREMAININGOVERTIMEWORK
, STG.TASKREMAININGREGULARCOST
, STG.TASKREMAININGREGULARWORK
, STG.TASKREMAININGWORK
, STG.TASKRESOURCEPLANWORK
, STG.TASKSPI
, STG.TASKSTARTDATE
, STG.TASKSTARTDATESTRING
, STG.TASKSTARTVARIANCE
, STG.TASKSTATUSMANAGERUID
, STG.TASKSV
, STG.TASKSVP
, STG.TASKTCPI
, STG.TASKTOTALSLACK
, STG.TASKVAC
, STG.TASKWBS
, STG.TASKWORK
, STG.TASKWORKVARIANCE
, STG.LINKEDASSIGNMENTS
, STG.LINKEDASSIGNMENTSBASELINES
, STG.LINKEDASSIGNMENTSBASELINETIMEPHASEDDATA
, STG.LINKEDBASELINES
, STG.LINKEDBASELINESTIMEPHASEDDATASET
, STG.LINKEDISSUES
, STG.LINKEDPROJECT
, STG.LINKEDRISKS
,STG.LINKEDTIMEPHASEDINFO
,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_INS_DTTM 
    ,'{{V_START_DTTM}}'::TIMESTAMP_NTZ BIW_UPD_DTTM 
   ,{{V_BIW_BATCH_ID}}::NUMBER as BIW_BATCH_ID 
   ,md5(object_construct ('COL1',PROJECTID::string ,'COL2',TASKID::string ,'COL3',DETECTABILITY::string ,'COL4',FLAGSTATUS::string ,'COL5',HEALTH::string ,'COL6',IMPACT::string ,'COL7',MITIGATIONFLAG::string ,'COL8',NPDGATE::string ,'COL9',NPDMILESTONE::string ,'COL10',PARENTTASKID::string ,'COL11',PARENTTASKNAME::string ,'COL12',PROBABILITY::string ,'COL13',PROJECTNAME::string ,'COL14',RISK::string ,'COL15',RISKFLAG::string ,'COL16',RISKLEVEL::string ,'COL17',RISKSCORE::string ,'COL18',TASKACTUALCOST::string ,'COL19',TASKACTUALDURATION::string ,'COL20',TASKACTUALFINISHDATE::string ,'COL21',TASKACTUALFIXEDCOST::string ,'COL22',TASKACTUALOVERTIMECOST::string ,'COL23',TASKACTUALOVERTIMEWORK::string ,'COL24',TASKACTUALREGULARCOST::string ,'COL25',TASKACTUALREGULARWORK::string ,'COL26',TASKACTUALSTARTDATE::string ,'COL27',TASKACTUALWORK::string ,'COL28',TASKACWP::string ,'COL29',TASKBCWP::string ,'COL30',TASKBCWS::string ,'COL31',TASKBUDGETCOST::string ,'COL32',TASKBUDGETWORK::string ,'COL33',TASKCLIENTUNIQUEID::string ,'COL34',TASKCOST::string ,'COL35',TASKCOSTVARIANCE::string ,'COL36',TASKCPI::string ,'COL37',TASKCREATEDDATE::string ,'COL38',TASKCREATEDREVISIONCOUNTER::string ,'COL39',TASKCV::string ,'COL40',TASKCVP::string ,'COL41',TASKDEADLINE::string ,'COL42',TASKDELIVERABLEFINISHDATE::string ,'COL43',TASKDELIVERABLESTARTDATE::string ,'COL44',TASKDURATION::string ,'COL45',TASKDURATIONISESTIMATED::string ,'COL46',TASKDURATIONSTRING::string ,'COL47',TASKDURATIONVARIANCE::string ,'COL48',TASKEAC::string ,'COL49',TASKEARLYFINISH::string ,'COL50',TASKEARLYSTART::string ,'COL51',TASKFINISHDATE::string ,'COL52',TASKFINISHDATESTRING::string ,'COL53',TASKFINISHVARIANCE::string ,'COL54',TASKFIXEDCOST::string ,'COL55',TASKFIXEDCOSTASSIGNMENTID::string ,'COL56',TASKFREESLACK::string ,'COL57',TASKHYPERLINKADDRESS::string ,'COL58',TASKHYPERLINKFRIENDLYNAME::string ,'COL59',TASKHYPERLINKSUBADDRESS::string ,'COL60',TASKIGNORESRESOURCECALENDAR::string ,'COL61',TASKINDEX::string ,'COL62',TASKISACTIVE::string ,'COL63',TASKISCRITICAL::string ,'COL64',TASKISEFFORTDRIVEN::string ,'COL65',TASKISEXTERNAL::string ,'COL66',TASKISMANUALLYSCHEDULED::string ,'COL67',TASKISMARKED::string ,'COL68',TASKISMILESTONE::string ,'COL69',TASKISOVERALLOCATED::string ,'COL70',TASKISPROJECTSUMMARY::string ,'COL71',TASKISRECURRING::string ,'COL72',TASKISSUMMARY::string ,'COL73',TASKLATEFINISH::string ,'COL74',TASKLATESTART::string ,'COL75',TASKLEVELINGDELAY::string ,'COL76',TASKMODIFIEDDATE::string ,'COL77',TASKMODIFIEDREVISIONCOUNTER::string ,'COL78',TASKNAME::string ,'COL79',TASKOUTLINELEVEL::string ,'COL80',TASKOUTLINENUMBER::string ,'COL81',TASKOVERTIMECOST::string ,'COL82',TASKOVERTIMEWORK::string ,'COL83',TASKPERCENTCOMPLETED::string ,'COL84',TASKPERCENTWORKCOMPLETED::string ,'COL85',TASKPHYSICALPERCENTCOMPLETED::string ,'COL86',TASKPRIORITY::string ,'COL87',TASKREGULARCOST::string ,'COL88',TASKREGULARWORK::string ,'COL89',TASKREMAININGCOST::string ,'COL90',TASKREMAININGDURATION::string ,'COL91',TASKREMAININGOVERTIMECOST::string ,'COL92',TASKREMAININGOVERTIMEWORK::string ,'COL93',TASKREMAININGREGULARCOST::string ,'COL94',TASKREMAININGREGULARWORK::string ,'COL95',TASKREMAININGWORK::string ,'COL96',TASKRESOURCEPLANWORK::string ,'COL97',TASKSPI::string ,'COL98',TASKSTARTDATE::string ,'COL99',TASKSTARTDATESTRING::string ,'COL100',TASKSTARTVARIANCE::string ,'COL101',TASKSTATUSMANAGERUID::string ,'COL102',TASKSV::string ,'COL103',TASKSVP::string ,'COL104',TASKTCPI::string ,'COL105',TASKTOTALSLACK::string ,'COL106',TASKVAC::string ,'COL107',TASKWBS::string ,'COL108',TASKWORK::string ,'COL109',TASKWORKVARIANCE::string ,'COL110',LINKEDASSIGNMENTS::string ,'COL111',LINKEDASSIGNMENTSBASELINES::string ,'COL112',LINKEDASSIGNMENTSBASELINETIMEPHASEDDATA::string ,'COL113',LINKEDBASELINES::string ,'COL114',LINKEDBASELINESTIMEPHASEDDATASET::string ,'COL115',LINKEDISSUES::string ,'COL116',LINKEDPROJECT::string ,'COL117',LINKEDRISKS::string ,'COL118',LINKEDTIMEPHASEDINFO::string )::string )::BINARY as BIW_MD5_KEY

FROM     
TASKS  STG 

CROSS JOIN FISCAL_WEEK FSC_WK
