--[   NPD_MSPROJECTS_PROJECTWORKFLOWSTAGEDATASET_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF PROJECTWORKFLOWSTAGEDATASET ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_PROJECTWORKFLOWSTAGEDATASET_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
PROJECTWORKFLOWSTAGEDATASET_KEY
, SNAPSHOT_WEEK_KEY
,PROJECTID
, STAGEID
, LASTMODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',LASTMODIFIEDDATE) AS BIW_LASTMODIFIEDDATE_MST
, LCID
, PHASEDESCRIPTION
, PHASENAME
, PROJECTNAME
, STAGECOMPLETIONDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',STAGECOMPLETIONDATE) AS BIW_STAGECOMPLETIONDATE_MST
, STAGEDESCRIPTION
, STAGEENTRYDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',STAGEENTRYDATE) AS BIW_STAGEENTRYDATE_MST
, STAGEINFORMATION
, STAGELASTSUBMITTEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',STAGELASTSUBMITTEDDATE) AS BIW_STAGELASTSUBMITTEDDATE_MST
, STAGENAME
, STAGEORDER
, STAGESTATEDESCRIPTION
, STAGESTATUS
, LINKEDPROJECT
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_PROJECTWORKFLOWSTAGEDATASET_WEEKLY_SNAPSHOT')}}  
