--[   NPD_MSPROJECTS_ENGAGEMENTSTIMEPHASEDDATASET_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF ENGAGEMENTSTIMEPHASEDDATASET ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_ENGAGEMENTSTIMEPHASEDDATASET_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
ENGAGEMENTSTIMEPHASEDDATASET_KEY
, SNAPSHOT_WEEK_KEY
,ENGAGEMENTID
, TIMEBYDAY , CONVERT_TIMEZONE('UTC','America/Phoenix',TIMEBYDAY) AS BIW_TIMEBYDAY_MST
, COMMITTEDMAXUNITS
, COMMITTEDWORK
, ENGAGEMENTMODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',ENGAGEMENTMODIFIEDDATE) AS BIW_ENGAGEMENTMODIFIEDDATE_MST
, ENGAGEMENTNAME
, PROJECTID
, PROJECTNAME
, PROPOSEDMAXUNITS
, PROPOSEDWORK
, RESOURCEID
, RESOURCENAME
, LINKEDENGAGEMENT
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_ENGAGEMENTSTIMEPHASEDDATASET_WEEKLY_SNAPSHOT')}}  
