--[   NPD_MSPROJECTS_PRIORITIZATIONS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF PRIORITIZATIONS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_PRIORITIZATIONS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
PRIORITIZATIONS_KEY
, SNAPSHOT_WEEK_KEY
,PRIORITIZATIONID
, CONSISTENCYRATIO
, CREATEDBYRESOURCEID
, CREATEDBYRESOURCENAME
, DEPARTMENTID
, DEPARTMENTNAME
, MODIFIEDBYRESOURCEID
, MODIFIEDBYRESOURCENAME
, PRIORITIZATIONCREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PRIORITIZATIONCREATEDDATE) AS BIW_PRIORITIZATIONCREATEDDATE_MST
, PRIORITIZATIONDESCRIPTION
, PRIORITIZATIONISMANUAL
, PRIORITIZATIONMODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PRIORITIZATIONMODIFIEDDATE) AS BIW_PRIORITIZATIONMODIFIEDDATE_MST
, PRIORITIZATIONNAME
, LINKEDCREATEDBYRESOURCE
, LINKEDMODIFIEDBYRESOURCE
, LINKEDPRIORITIZATIONDRIVERRELATIONS
, LINKEDPRIORITIZATIONDRIVERS
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_PRIORITIZATIONS_WEEKLY_SNAPSHOT')}}  
