--[   NPD_MSPROJECTS_COSTSCENARIOPROJECTS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF COSTSCENARIOPROJECTS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_COSTSCENARIOPROJECTS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
COSTSCENARIOPROJECTS_KEY
, SNAPSHOT_WEEK_KEY
,PROJECTID
, SCENARIOID
, ABSOLUTEPRIORITY
, ANALYSISID
, ANALYSISNAME
, FORCEALIASLOOKUPTABLEID
, FORCEALIASLOOKUPTABLENAME
, FORCESTATUS
, HARDCONSTRAINTVALUE
, PRIORITY
, PROJECTNAME
, SCENARIONAME
, STATUS
, LINKEDANALYSIS
, LINKEDCOSTCONSTRAINTSCENARIO
, LINKEDPROJECT
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_COSTSCENARIOPROJECTS_WEEKLY_SNAPSHOT')}}  
