--[   NPD_MSPROJECTS_TIMESHEETCLASSES_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF TIMESHEETCLASSES ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_TIMESHEETCLASSES_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
TIMESHEETCLASSES_KEY
, SNAPSHOT_WEEK_KEY
,DEPARTMENTID
, TIMESHEETCLASSID
, DEPARTMENTNAME
, DESCRIPTION
, LCID
, TIMESHEETCLASSNAME
, TIMESHEETCLASSTYPE
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_TIMESHEETCLASSES_WEEKLY_SNAPSHOT')}}  
