--[   NPD_MSPROJECTS_PRIORITIZATIONDRIVERS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF PRIORITIZATIONDRIVERS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_PRIORITIZATIONDRIVERS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
PRIORITIZATIONDRIVERS_KEY
, SNAPSHOT_WEEK_KEY
,BUSINESSDRIVERID
, PRIORITIZATIONID
, BUSINESSDRIVERNAME
, BUSINESSDRIVERPRIORITY
, PRIORITIZATIONNAME
, LINKEDBUSINESSDRIVER
, LINKEDPRIORITIZATION
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_PRIORITIZATIONDRIVERS_WEEKLY_SNAPSHOT')}}  
