--[   NPD_MSPROJECTS_PORTFOLIOANALYSISPROJECTS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF PORTFOLIOANALYSISPROJECTS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_PORTFOLIOANALYSISPROJECTS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
PORTFOLIOANALYSISPROJECTS_KEY
, SNAPSHOT_WEEK_KEY
,ANALYSISID
, PROJECTID
, ABSOLUTEPRIORITY
, ANALYSISNAME
, DURATION
, FINISHNOLATERTHAN , CONVERT_TIMEZONE('UTC','America/Phoenix',FINISHNOLATERTHAN) AS BIW_FINISHNOLATERTHAN_MST
, LOCKED
, ORIGINALENDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',ORIGINALENDDATE) AS BIW_ORIGINALENDDATE_MST
, ORIGINALSTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',ORIGINALSTARTDATE) AS BIW_ORIGINALSTARTDATE_MST
, PRIORITY
, PROJECTNAME
, STARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',STARTDATE) AS BIW_STARTDATE_MST
, STARTNOEARLIERTHAN , CONVERT_TIMEZONE('UTC','America/Phoenix',STARTNOEARLIERTHAN) AS BIW_STARTNOEARLIERTHAN_MST
, LINKEDANALYSIS
, LINKEDPROJECT
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_PORTFOLIOANALYSISPROJECTS_WEEKLY_SNAPSHOT')}}  
