--[   NPD_MSPROJECTS_BUSINESSDRIVERS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF BUSINESSDRIVERS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_BUSINESSDRIVERS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
BUSINESSDRIVERS_KEY
, SNAPSHOT_WEEK_KEY
,BUSINESSDRIVERID
, BUSINESSDRIVERCREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',BUSINESSDRIVERCREATEDDATE) AS BIW_BUSINESSDRIVERCREATEDDATE_MST
, BUSINESSDRIVERDESCRIPTION
, BUSINESSDRIVERISACTIVE
, BUSINESSDRIVERMODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',BUSINESSDRIVERMODIFIEDDATE) AS BIW_BUSINESSDRIVERMODIFIEDDATE_MST
, BUSINESSDRIVERNAME
, CREATEDBYRESOURCEID
, CREATEDBYRESOURCENAME
, IMPACTDESCRIPTIONEXTREME
, IMPACTDESCRIPTIONLOW
, IMPACTDESCRIPTIONMODERATE
, IMPACTDESCRIPTIONNONE
, IMPACTDESCRIPTIONSTRONG
, MODIFIEDBYRESOURCEID
, MODIFIEDBYRESOURCENAME
, LINKEDCREATEDBYRESOURCE
, LINKEDDEPARTMENTS
, LINKEDMODIFIEDBYRESOURCE
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_BUSINESSDRIVERS_WEEKLY_SNAPSHOT')}}  
