--[   NPD_MSPROJECTS_DELIVERABLES_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF DELIVERABLES ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_DELIVERABLES_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
DELIVERABLES_KEY
, SNAPSHOT_WEEK_KEY
,DELIVERABLEID
, PROJECTID
, CREATEBYRESOURCE
, CREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',CREATEDDATE) AS BIW_CREATEDDATE_MST
, DESCRIPTION
, FINISHDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',FINISHDATE) AS BIW_FINISHDATE_MST
, ISFOLDER
, ITEMRELATIVEURLPATH
, MODIFIEDBYRESOURCE
, MODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',MODIFIEDDATE) AS BIW_MODIFIEDDATE_MST
, PROJECTNAME
, STARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',STARTDATE) AS BIW_STARTDATE_MST
, TITLE
, LINKEDDEPENDENTPROJECTS
, LINKEDDEPENDENTTASKS
, LINKEDPARENTPROJECTS
, LINKEDPARENTTASKS
, LINKEDPROJECT
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_DELIVERABLES_WEEKLY_SNAPSHOT')}}  
