--[   NPD_MSPROJECTS_TASKBASELINES_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF TASKBASELINES ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_TASKBASELINES_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
TASKBASELINES_KEY
, SNAPSHOT_WEEK_KEY
,BASELINENUMBER
, PROJECTID
, TASKID
, PROJECTNAME
, TASKBASELINEBUDGETCOST
, TASKBASELINEBUDGETWORK
, TASKBASELINECOST
, TASKBASELINEDELIVERABLEFINISHDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKBASELINEDELIVERABLEFINISHDATE) AS BIW_TASKBASELINEDELIVERABLEFINISHDATE_MST
, TASKBASELINEDELIVERABLESTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKBASELINEDELIVERABLESTARTDATE) AS BIW_TASKBASELINEDELIVERABLESTARTDATE_MST
, TASKBASELINEDURATION
, TASKBASELINEDURATIONSTRING
, TASKBASELINEFINISHDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKBASELINEFINISHDATE) AS BIW_TASKBASELINEFINISHDATE_MST
, TASKBASELINEFINISHDATESTRING
, TASKBASELINEFIXEDCOST
, TASKBASELINEMODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKBASELINEMODIFIEDDATE) AS BIW_TASKBASELINEMODIFIEDDATE_MST
, TASKBASELINESTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TASKBASELINESTARTDATE) AS BIW_TASKBASELINESTARTDATE_MST
, TASKBASELINESTARTDATESTRING
, TASKBASELINEWORK
, TASKNAME
, LINKEDPROJECT
, LINKEDTASK
, LINKEDTASKBASELINETIMEPHASEDDATASET
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_TASKBASELINES_WEEKLY_SNAPSHOT')}}  
