--[   NPD_MSPROJECTS_RISKS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF RISKS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_RISKS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
RISKS_KEY
, SNAPSHOT_WEEK_KEY
,PROJECTID
, RISKID
, ASSIGNEDTORESOURCE
, CATEGORY
, CONTINGENCYPLAN
, COST
, COSTEXPOSURE
, CREATEBYRESOURCE
, CREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',CREATEDDATE) AS BIW_CREATEDDATE_MST
, DESCRIPTION
, DUEDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',DUEDATE) AS BIW_DUEDATE_MST
, EXPOSURE
, IMPACT
, ISFOLDER
, ITEMRELATIVEURLPATH
, MITIGATIONPLAN
, MODIFIEDBYRESOURCE
, MODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',MODIFIEDDATE) AS BIW_MODIFIEDDATE_MST
, NUMBEROFATTACHMENTS
, OWNER
, PROBABILITY
, PROJECTNAME
, STATUS
, TITLE
, TRIGGERDESCRIPTION
, TRIGGERTASK
, LINKEDPROJECT
, LINKEDRELATEDISSUES
, LINKEDSUBRISKS
, LINKEDTASKS
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_RISKS_WEEKLY_SNAPSHOT')}}  
