--[   NPD_MSPROJECTS_PRIORITIZATIONDRIVERRELATIONS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF PRIORITIZATIONDRIVERRELATIONS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_PRIORITIZATIONDRIVERRELATIONS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
PRIORITIZATIONDRIVERRELATIONS_KEY
, SNAPSHOT_WEEK_KEY
,BUSINESSDRIVER1ID
, BUSINESSDRIVER2ID
, PRIORITIZATIONID
, BUSINESSDRIVER1NAME
, BUSINESSDRIVER2NAME
, PRIORITIZATIONNAME
, RELATIONVALUE
, LINKEDBUSINESSDRIVER1
, LINKEDBUSINESSDRIVER2
, LINKEDPRIORITIZATION
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_PRIORITIZATIONDRIVERRELATIONS_WEEKLY_SNAPSHOT')}}  
