--[   NPD_MSPROJECTS_TIMESHEETLINEACTUALDATASET_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF TIMESHEETLINEACTUALDATASET ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_TIMESHEETLINEACTUALDATASET_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
TIMESHEETLINEACTUALDATASET_KEY
, SNAPSHOT_WEEK_KEY
,ADJUSTMENTINDEX
, TIMEBYDAY , CONVERT_TIMEZONE('UTC','America/Phoenix',TIMEBYDAY) AS BIW_TIMEBYDAY_MST
, TIMESHEETLINEID
, ACTUALOVERTIMEWORKBILLABLE
, ACTUALOVERTIMEWORKNONBILLABLE
, ACTUALWORKBILLABLE
, ACTUALWORKNONBILLABLE
, COMMENT
, CREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',CREATEDDATE) AS BIW_CREATEDDATE_MST
, LASTCHANGEDRESOURCENAME
, PLANNEDWORK
, RESOURCENAME
, TIMEBYDAY_DAYOFMONTH
, TIMEBYDAY_DAYOFWEEK
, TIMESHEETLINEMODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',TIMESHEETLINEMODIFIEDDATE) AS BIW_TIMESHEETLINEMODIFIEDDATE_MST
, LINKEDLASTCHANGEDBYRESOURCE
, LINKEDTIME
, LINKEDTIMESHEETLINE
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_TIMESHEETLINEACTUALDATASET_WEEKLY_SNAPSHOT')}}  
