--[   NPD_MSPROJECTS_ENGAGEMENTS_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF ENGAGEMENTS ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_ENGAGEMENTS_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
ENGAGEMENTS_KEY
, SNAPSHOT_WEEK_KEY
,ENGAGEMENTID
, COMMITTEDFINISHDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',COMMITTEDFINISHDATE) AS BIW_COMMITTEDFINISHDATE_MST
, COMMITTEDMAXUNITS
, COMMITTEDSTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',COMMITTEDSTARTDATE) AS BIW_COMMITTEDSTARTDATE_MST
, COMMITTEDWORK
, ENGAGEMENTCREATEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',ENGAGEMENTCREATEDDATE) AS BIW_ENGAGEMENTCREATEDDATE_MST
, ENGAGEMENTMODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',ENGAGEMENTMODIFIEDDATE) AS BIW_ENGAGEMENTMODIFIEDDATE_MST
, ENGAGEMENTNAME
, ENGAGEMENTREVIEWEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',ENGAGEMENTREVIEWEDDATE) AS BIW_ENGAGEMENTREVIEWEDDATE_MST
, ENGAGEMENTSTATUS
, ENGAGEMENTSUBMITTEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',ENGAGEMENTSUBMITTEDDATE) AS BIW_ENGAGEMENTSUBMITTEDDATE_MST
, MODIFIEDBYRESOURCEID
, MODIFIEDBYRESOURCENAME
, PROJECTID
, PROJECTNAME
, PROPOSEDFINISHDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROPOSEDFINISHDATE) AS BIW_PROPOSEDFINISHDATE_MST
, PROPOSEDMAXUNITS
, PROPOSEDSTARTDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',PROPOSEDSTARTDATE) AS BIW_PROPOSEDSTARTDATE_MST
, PROPOSEDWORK
, RESOURCEID
, RESOURCENAME
, REVIEWEDBYRESOURCEID
, REVIEWEDBYRESOURCENAME
, SUBMITTEDBYRESOURCEID
, SUBMITTEDBYRESOURCENAME
, LINKEDCOMMENT
, LINKEDTIMEPHASEDINFO
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_ENGAGEMENTS_WEEKLY_SNAPSHOT')}}  
