--[   NPD_MSPROJECTS_ASSIGNMENTTIMEPHASEDDATASET_WEEKLY_SNAPSHOT    ]
{{ 
config
(
description = 'NPD LANDING PAGE DATA DISCOVERY VIEW OF ASSIGNMENTTIMEPHASEDDATASET ', 
materialized = 'view', 
schema = 'NPD', 
tags = ['ODS_NPD'],
alias = 'MSPROJECTS_ASSIGNMENTTIMEPHASEDDATASET_WEEKLY_SNAPSHOT'
) 
}}

SELECT  
ASSIGNMENTTIMEPHASEDDATASET_KEY
, SNAPSHOT_WEEK_KEY
,ASSIGNMENTID
, PROJECTID
, TIMEBYDAY , CONVERT_TIMEZONE('UTC','America/Phoenix',TIMEBYDAY) AS BIW_TIMEBYDAY_MST
, ASSIGNMENTACTUALCOST
, ASSIGNMENTACTUALOVERTIMECOST
, ASSIGNMENTACTUALOVERTIMEWORK
, ASSIGNMENTACTUALREGULARCOST
, ASSIGNMENTACTUALREGULARWORK
, ASSIGNMENTACTUALWORK
, ASSIGNMENTBUDGETCOST
, ASSIGNMENTBUDGETMATERIALWORK
, ASSIGNMENTBUDGETWORK
, ASSIGNMENTCOMBINEDWORK
, ASSIGNMENTCOST
, ASSIGNMENTMATERIALACTUALWORK
, ASSIGNMENTMATERIALWORK
, ASSIGNMENTMODIFIEDDATE , CONVERT_TIMEZONE('UTC','America/Phoenix',ASSIGNMENTMODIFIEDDATE) AS BIW_ASSIGNMENTMODIFIEDDATE_MST
, ASSIGNMENTOVERTIMECOST
, ASSIGNMENTOVERTIMEWORK
, ASSIGNMENTREGULARCOST
, ASSIGNMENTREGULARWORK
, ASSIGNMENTREMAININGCOST
, ASSIGNMENTREMAININGOVERTIMECOST
, ASSIGNMENTREMAININGOVERTIMEWORK
, ASSIGNMENTREMAININGREGULARCOST
, ASSIGNMENTREMAININGREGULARWORK
, ASSIGNMENTREMAININGWORK
, ASSIGNMENTRESOURCEPLANWORK
, ASSIGNMENTWORK
, FISCALPERIODID
, PROJECTNAME
, RESOURCEID
, TASKID
, TASKISACTIVE
, TASKNAME
, LINKEDASSIGNMENT
, LINKEDPROJECT
, LINKEDTASK
, LINKEDTIME
, BIW_INS_DTTM
, BIW_UPD_DTTM
, BIW_BATCH_ID, BIW_MD5_KEY 
FROM 
{{ref ('ODS_NPD_MSPROJECTS_ASSIGNMENTTIMEPHASEDDATASET_WEEKLY_SNAPSHOT')}}  
